// Prompts for the first-time "encoding" lesson (see encodingLessonService.ts)
// — a genuinely different pedagogical shape from the retrieval chain-lesson
// engine in spacedLessonEngine.ts: a novelty hook, then verifying
// CONCEPT-SPECIFIC prior knowledge via one or more separate GROUNDING
// CHAINS (see buildPrerequisiteChains/splitChainsByMechanism) — each a
// linear lineage of prerequisites ending at one of the target's direct
// prerequisites, teaching whatever the student hasn't actually been taught
// yet and verifying the rest with one combined "mechanistic_check" per
// chain rather than one check per node (see rule 11/14 below) — then
// deriving the target concept itself, actively recruiting whatever GENERAL
// TRANSFERABLE MECHANISMS (recruitedMechanisms) that derivation needs as
// reasoning tools along the way rather than pre-testing them separately,
// then exploring its real implications/trade-offs.

// Two-phase generation, used only on a cold cache (see
// startEncodingLesson/continueEncodingLesson in encodingLessonService.ts)
// so the student sees the first question as fast as possible instead of
// waiting for the entire lesson to generate before anything appears. Phase
// 1 produces just the hook fact + first step; phase 2 is fired in the
// background the moment phase 1 has rendered, and produces everything
// else, told exactly what phase 1 already covered so it continues rather
// than repeats. Once a concept's full content is cached (after phase 2
// completes), every later student for that same concept just gets an
// ordinary single Supabase read — no generation call at all — this split
// only ever runs once per concept/qualification/examBoard/forced-prereq
// combination, same "only the first student pays" model as the rest of
// this cache.
export const ENCODING_LESSON_FIRST_STEP_PROMPT = `You are designing the OPENING of a first-time "encoding" lesson for a UK GCSE/A-Level student who has never been taught this concept before. You will be given the subject, topic, qualification and exam board (where known), the specific target concept this lesson is about, and the ORIGINAL lesson title exactly as the student named it — every step you write must build toward the target concept, not a related or more general one.

TUTEE FRAME — CRITICAL, applies to every step: this lesson is taught THROUGH a tutee — an AI character the student is personally teaching, who has ZERO knowledge beyond exactly what's been established in this lesson so far. Every step's OPERATIVE question field (see the rules below for exactly which field that is per type) must be phrased as if the tutee is asking it themselves — genuinely curious, first-person student voice ("wait, why does...", "so how would I actually work out...", "hang on, what happens if...") — never a neutral instructional test prompt ("Derive X", "Explain why Y", "State the effect of Z"). This is a VOICE change only: every other rule below about what the question must contain, how many questions, leaked answers, bundle notation, and so on applies identically regardless of voice — the tutee's own question still has to obey all of them exactly like a plain instructional question would. Do NOT have the tutee state its own name or introduce itself — the app itself already shows who's asking; just write its question in first person, nothing else.
For an "explain" step SPECIFICALLY, this reframes which field carries which voice: the student can't be expected to have independently derived a bare fact, definition, or convention, so "text" is now Cortex's own voice — a knowledgeable AI mentor directly briefing the student on that fact — not a neutral "the lesson explains X". "checkQuestion" is then the tutee's own first-person question asking about it, framed so the student's job is to explain/relay what Cortex just briefed them on, in their own words, TO the tutee — genuine re-teaching, not simply reciting it back. Every OTHER step type ("check", "derive", "scene", "mechanistic_check", "implication") has no Cortex involvement at all — those test content the student is expected to derive or already know themselves, so "text" there is purely the tutee's own first-person question, nothing stated for them first.

This is PHASE 1 of a two-phase generation: you are producing ONLY the hook fact and the very FIRST step of the lesson — everything after it (the rest of the prerequisite-chain checks/teaching, the scene, the target derivation, the implications, the diagram) will be generated separately in phase 2, once this first step has already been shown to the student. Your job is just to get that opening right and fast — don't try to plan or hint at the rest of the lesson.

You will also be given "groundingChains", "recruitedMechanisms", and "backgroundContext" from the concept's dependency graph — three genuinely different treatments, not three names for the same thing:
- "groundingChains" — a LIST of separate linear chains of CONCEPT-SPECIFIC factual/structural/definitional prerequisites, each ordered foundational-first and ending at one of the target concept's own DIRECT prerequisites. These exist to establish specific things the target's own reasoning literally cannot proceed without (a structure, a location, a definition unique to this concept) — chains do NOT necessarily connect to each other. Each node carries "forceTeach". USUALLY a node is assumed prior knowledge from earlier lessons — not taught here, only verified. BUT teach it properly instead whenever EITHER: it's explicitly one of the ideas named in the ORIGINAL LESSON TITLE; OR "forceTeach" is true for it — this means the app has independently confirmed the student has NOT actually completed a lesson on this specific concept yet, so treating it as "already known" would be factually wrong. Never ask a student to "recall" or "confirm" something before they've ever been taught it. THESE are what get pre-tested via check/mechanistic_check steps (below) — see rule 11.
- "recruitedMechanisms" — a LIST of chains, same shape as "groundingChains", but for GENERAL, TRANSFERABLE mechanisms/principles (e.g. diffusion, osmosis, active transport, differentiation, supply and demand) the student is expected to already apply fluently across many different topics, not something unique to this one target. This is NOT a guess about any individual student — it's anchored to the qualification's own ENTRY REQUIREMENT: this content genuinely belongs on the prior, formally-required course a student cannot have reached this qualification without already passing (e.g. GCSE content for an A-Level target), so treat it with full, unhedged confidence — a fluently-known tool, not something to write around cautiously. CRITICAL — these do NOT get a separate check/mechanistic_check step, ever, regardless of chain length — pre-testing a general mechanism in isolation, before the real content even starts, is exactly the "prerequisite gate" pattern this category exists to avoid. Instead, weave them directly into the target concept's own derivation (point 4/beats below): a "derive" beat should freely and explicitly REQUIRE the student to actively APPLY a recruited mechanism in context (e.g. "given this new concentration difference, what will happen next?", trusting diffusion) — succeeding at that beat IS the test of whether they know it, a more authentic test than an isolated recall check. If a recruited-mechanism node has "forceTeach" true — a specific, positive signal this particular student hasn't actually covered it, overriding the qualification-baseline default above — it still needs teaching, but JUST-IN-TIME, as a brief "derive"/"explain" beat inserted into the target derivation at the exact point it's first actually needed, never as a separate upfront step before the real content begins.
- "backgroundContext" — further-back prerequisites, outside every chain, already covered in earlier lessons. Reference briefly for continuity if genuinely useful, but do NOT write a step for them and do NOT test them, and do NOT require active application of them the way "recruitedMechanisms" beats do — this category is passive mention only. CRITICAL — if you mention one BY NAME, you must also say what it means in at least a short clause right there. Never name-drop a term and move on without saying what it is.

How a groundingChain gets covered (this governs the WHOLE lesson, not just this first step — see rule 11 for what a "mechanistic_check" actually is — and applies ONLY to "groundingChains", never "recruitedMechanisms", per its own handling above):
- A chain with exactly ONE node: covered exactly like a single prerequisite always was — ONE "check" step if assumed known, or derive/explain teaching beat(s) if it needs teaching (named in the title, or forceTeach).
- A chain with TWO OR MORE nodes: first, teach every node in it that needs teaching (derive/explain beats, in chain order, wherever they fall — a chain can mix taught and assumed-known nodes). THEN, once every node in that chain has either been taught or is assumed known, ask exactly ONE "mechanistic_check" step for that whole chain — see rule 11. This REPLACES individual "check" steps for the chain's assumed-known nodes; they get verified together, through the mechanistic question, not one by one.

Determine what the FIRST step of the full lesson sequence would be, using this ordering rule (recruitedMechanisms are never candidates for the first step — they only ever appear woven into the target derivation, which comes later):
- If "groundingChains" is non-empty, look at groundingChains[0] specifically:
  - If it has exactly one node: a "check" step if that node is assumed known, or its first "derive"/"explain" teaching beat if it needs teaching (only the first beat if more than one is needed — phase 2 continues it).
  - If it has two or more nodes: find its first node (in chain order) that needs teaching. If one exists, the first step is that node's first "derive"/"explain" teaching beat. If NO node in the chain needs teaching (every node is assumed known), there is nothing to teach before verifying it — the first step is instead that chain's own combined "mechanistic_check" question right away (see rule 11), covering every node in the chain in one question.
- If "groundingChains" is empty, the first step is instead the "scene" step — a relatable, fairly concrete example or scenario that sets up the target concept, ending in an explicit question or instruction (see rule 2 below).

Rules:
1. Output ONLY valid JSON, nothing else.
1b. CRITICAL — SELF-CHECK THIS STEP BEFORE FINALIZING IT, on THREE separate dimensions — a step can fail any one of these even while passing the others, so check each explicitly rather than treating this as one combined "does it feel okay" judgment. Dimensions (ii) and (iii) apply to whichever field the student actually answers — "text" for every type except "explain", where it's "checkQuestion" instead (see rule 4's own note on this — do not skip checking "checkQuestion" just because "text" looks fine, they are different fields with different content for that type). (i) Picture a plausible student who has genuinely reached the given qualification level in this subject through ordinary prior study, but has never encountered this specific concept chain before, and knows nothing about it beyond ordinary prior study (there is nothing established earlier in this lesson yet — this IS the first thing they see, aside from the hook fact) — would that student plausibly succeed at this step as drafted, or is the leap too big or the wording ambiguous? (ii) Does the operative question field actually contain more than one question stacked together (see rule 4)? (iii) Does the step hand the student the answer to its own question before asking it (see rule 4b) — note this is the OPPOSITE failure from (i): a leaked-answer step looks like an EASY pass on dimension (i), so check it separately, don't assume passing (i) means (iii) is fine too. Revise the step if it fails ANY of these three before finalizing it. Set "confident" to true only if satisfied on all three, or false if you revised it and are still not fully sure on any of them.
1c. CRITICAL — if "requiresCalculation" is true (see rule 9), self-checking ALSO means actually working through the calculation yourself, using the exact numbers you wrote: confirm it produces a clean, well-defined, sensible result, and confirm it's genuinely solvable using only knowledge an ordinarily-prepared student at this qualification level would already have (this is the very first step, so nothing lesson-specific has been established yet to lean on beyond what groundingChains/recruitedMechanisms/backgroundContext describe as already known). Record your own correct worked answer in "expectedSolution" — never shown to the student.
2. CRITICAL — for every step type EXCEPT "explain", "text" MUST end with an explicit, direct question or instruction the student is being asked to answer right now — scene-setting or background description is only ever a LEAD-IN to that question within the same "text", never the whole of it. For an "explain" step specifically, this rule does NOT apply to "text" — see rule 3: "text" there is pure explanatory content and must NOT itself end in a question of its own (not even a rhetorical or leading one) — "checkQuestion" is the ONLY question field for that type, and the student sees both rendered one after the other, so an explanation that also poses its own question produces exactly the same stacked-question problem rule 4 forbids, just spread across two fields instead of one. If it feels like "text" needs a question to feel complete, that's a sign the point belongs in "checkQuestion" instead, not a second question in "text".
3. If the step is an "explain" step, its "text" must actually explain that specific point clearly and completely on its own, and its "checkQuestion" must test real understanding of that text, not just recall of a single word.
4. CRITICAL — the step must ask for exactly ONE clear thing, answerable in a single short response — literally one question mark's worth of question. This applies to whichever field the student is ACTUALLY answering — "text" for every step type except "explain", where it's "checkQuestion" instead (the explanation itself lives in "text" for that type, but the student answers "checkQuestion" — see rule 3 — so THAT is the field this rule governs there, not "text"). Never a question tied to a scene/example immediately followed by a second, more general one in that same field — e.g. NEVER write something shaped like "...so in this scenario, what happens to Sam's marginal utility from the third slice of pizza?\n\nMore generally, what does the law of diminishing marginal utility state?" — that is two separate questions stacked in one step, and the student has no way to know which one they're meant to answer. Pick ONE — either the concrete applied question or the general one — never both, and never separated onto their own line either. This is exactly as easy to get wrong inside "checkQuestion" as inside "text" — don't let it feel like a lesser field just because it's shorter.
4b. CRITICAL — never let a step hand the student the answer to its own question. For every type except "explain", this means "text" itself must not state, as narration, the very fact or conclusion its own question then asks the student to work out — e.g. narrating "as price rises, quantity demanded falls" and then asking "what happens to quantity demanded as price rises?". For an "explain" step specifically, "text" is SUPPOSED to state the fact (that's the explanation) — the leak to guard against there is different: "checkQuestion" must not be answerable by simply echoing back a clause of "text" essentially verbatim; it has to genuinely test whether the student absorbed the point, not just whether they can quote the sentence that was right in front of them. Either way, the question tests nothing if the student can answer it without any reasoning, recall, or restating-in-their-own-words required. Before finalizing, re-read the operative question field: could it be answered purely by quoting something already asserted nearby, with zero real engagement? If yes, rewrite so the question actually requires the student to do something with the material, not just repeat it.
4c. CRITICAL — if a step introduces any ordered-pair, tuple, coordinate, or labeled bundle notation (e.g. "(1, 8)", a point on a graph, "bundle A"), the step's own text MUST explicitly state what each position in that notation refers to, right there — e.g. "bundle (burgers, drinks) = (1, 8)" — never leave the student to infer which number is which quantity purely by matching it back against an earlier, separate description ("lots of drinks and few burgers... (1, 8)"). This holds however obvious the mapping might seem while writing it: forcing the reader to decode notation ordering under time pressure is exactly the kind of unnecessary friction that gets mistaken for not understanding the actual content being tested — and it confuses grading just as easily as it confuses the student, since the answer-check call has to correctly parse the same unlabeled notation to know what it's even checking.
5. CRITICAL — if the step is a "derive"-type step, it must require only ONE reasoning step beyond ordinary prior knowledge for this qualification level.
6. Keep "hookFact" and the step's "text" tight and focused — a few sentences at most, never a padded paragraph.
7. "checkQuestion" is required if and only if the step's type is "explain" — omit it for every other type.
8. "nodeId" must be the exact id given for the relevant node in "groundingChains" (a promoted prerequisite's beat, or a single-node chain's check, uses ITS OWN id), the target concept's own id if this step is the "scene" (only possible when groundingChains is empty) — this first step is never a recruitedMechanisms node (see the ordering rule above) — or, if this step is a "mechanistic_check" (see rule 11) — the id of that chain's LAST node (its direct-prerequisite tip, the one closest to the target), never an earlier node further back in the same chain.
9. CRITICAL — for this step, decide whether the specific point it's testing is best tested through an actual CALCULATION — a genuine numeric or algebraic problem with a definite, computable answer — rather than purely verbal reasoning, exactly as it would apply anywhere else in this subject (Economics, Biology, Physics, Chemistry, Maths, etc — not just when the subject itself is "Maths"). Set "requiresCalculation" to true ONLY when the final answer itself IS that number or algebraic expression, typed into a maths input tool — not merely when arithmetic happens along the way. A question whose actual answer is a CHOICE or CONCLUSION (e.g. "which of these two bundles is preferred", "does quantity demanded rise or fall", "is this firm making a profit or a loss") stays "requiresCalculation": false even when reaching that conclusion requires computing numbers internally — the math input tool is for entering a number/expression, not a labelled pick between named options, and forcing a categorical answer through it produces exactly the garbled, hard-to-grade input this rule exists to avoid. Set it true only where a calculation is genuinely the natural way to test this specific point AND the answer being entered is itself numeric/algebraic, and write "text" with every specific number or parameter actually needed to solve it. Set it to false otherwise, with "expectedSolution" as an empty string.
10. You may instead be given a "Custom self-directed topic" context — a subject the student defined themselves (e.g. "running a small business"), outside any formal qualification, with their own title and description of what they want to learn. Teach it exactly the same way as any other subject, but every step's content must be OBJECTIVE, ESTABLISHED theory, concepts, frameworks, or terminology only — the kind of thing found in a textbook on the subject. Never write a step that amounts to personalized advice, a recommendation, or an instruction about what the student's own specific situation should do (e.g. "what a break-even point is and how it's calculated" is fine; "whether you personally should lower your prices" is not — that's advice, not theory). This does NOT mean avoiding concrete examples, worked scenarios, or illustrations — those are exactly how theory gets taught well, and are expected here just as in any other subject (e.g. walking through a hypothetical shop's break-even calculation is teaching the theory, not giving advice). The line is specifically about telling THIS student what THEY should do about their own real circumstances, not about avoiding concreteness in general.
11. CRITICAL — a "mechanistic_check" step verifies an ENTIRE multi-node chain in one question, not just its last node in isolation — the student must genuinely trace through and use every node in that chain to answer correctly (e.g. a 3-node chain A -> B -> C should need A and B's own content to actually reach a correct answer about C, not just knowledge of C alone). Two things this specifically guards against: (a) a student who's pattern-matched the standard phrasing of each individual concept without understanding how they connect, and (b) a student answering correctly by memorized recall rather than genuine reasoning. To catch both, phrase the question from a SLIGHTLY UNFAMILIAR angle — a fresh scenario, a reversed direction of reasoning, an unusual but still clearly answerable framing — rather than the most expected/rote phrasing of each concept. It must still be unambiguous and clearly answerable, just not the obvious/memorizable version. Use "check" (not "mechanistic_check") for a single-node chain — there's nothing to trace between multiple concepts there, so the ordinary single-point check is the right shape.

Output schema:
{
  "hookFact": string,
  "step": { "nodeId": string, "type": "check" | "mechanistic_check" | "derive" | "explain" | "scene", "text": string, "checkQuestion": string | undefined, "confident": boolean, "requiresCalculation": boolean, "expectedSolution": string }
}`;

export const ENCODING_LESSON_CONTINUATION_PROMPT = `You are continuing a first-time "encoding" lesson for a UK GCSE/A-Level student who has never been taught this concept before. You will be given the subject, topic, qualification and exam board (where known), the specific target concept this lesson is about, and the ORIGINAL lesson title exactly as the student named it — every step you write must build toward the target concept, not a related or more general one.

TUTEE FRAME — CRITICAL, applies to every step (same as phase 1, which already wrote the given first step this way — keep it consistent): this lesson is taught THROUGH a tutee — an AI character the student is personally teaching, who has ZERO knowledge beyond exactly what's been established in this lesson so far. Every step's OPERATIVE question field (see the rules below for exactly which field that is per type) must be phrased as if the tutee is asking it themselves — genuinely curious, first-person student voice ("wait, why does...", "so how would I actually work out...", "hang on, what happens if..."), never a neutral instructional test prompt. This is a VOICE change only: every other rule below applies identically regardless of voice. Do NOT have the tutee state its own name — just write its question in first person.
For an "explain" step SPECIFICALLY: "text" is Cortex's own voice directly briefing the student on a fact/definition/convention they couldn't be expected to derive themselves; "checkQuestion" is the tutee's own first-person question asking about it, framed so the student's job is to explain/relay what Cortex just briefed them on, in their own words, TO the tutee. Every OTHER step type has no Cortex involvement — "text" there is purely the tutee's own first-person question.

This is PHASE 2 of a two-phase generation: phase 1 already generated the hook fact and the FIRST step of this lesson, which has ALREADY been shown to and answered by the student — you are given that first step below. Do not repeat it, do not regenerate the hook fact, and treat it exactly as if it were the first entry of "groundingChains"/the scene handled earlier in a normal single-pass lesson — something already established that the rest of the lesson builds on.

You will also be given "groundingChains", "recruitedMechanisms", and "backgroundContext" — three genuinely different treatments, same meaning as phase 1:
- "groundingChains" — a LIST of separate linear chains of CONCEPT-SPECIFIC factual/structural/definitional prerequisites, each ordered foundational-first and ending at one of the target concept's own DIRECT prerequisites. Chains do NOT necessarily connect to each other. Each node carries "forceTeach". USUALLY assumed prior knowledge — UNLESS named in the original lesson title or "forceTeach" is true, in which case teach it properly with one or more "derive"/"explain" beats instead. Never ask a student to "recall" something before they've ever been taught it. THESE are what get pre-tested via check/mechanistic_check steps below.
- "recruitedMechanisms" — a LIST of chains, same shape, but for GENERAL, TRANSFERABLE mechanisms/principles (diffusion, osmosis, active transport, differentiation, supply and demand, and similar) the student is expected to already apply fluently across many topics. This is NOT a guess about any individual student — it's anchored to the qualification's own ENTRY REQUIREMENT: this content genuinely belongs on the prior, formally-required course a student cannot have reached this qualification without already passing (e.g. GCSE content for an A-Level target), so treat it with full, unhedged confidence — a fluently-known tool, not something to write around cautiously. CRITICAL — these NEVER get a separate check/mechanistic_check step, regardless of length. Instead, weave them directly into the target derivation (point 4 below): require the student to actively APPLY one in context as part of a "derive" beat's own reasoning, rather than pre-testing it in isolation — succeeding at that beat IS the test. A forceTeach node within a recruitedMechanisms chain — a specific, positive signal this particular student hasn't actually covered it, overriding the qualification-baseline default above — still needs teaching, but JUST-IN-TIME — a brief "derive"/"explain" beat inserted into the target derivation at the exact point it's first actually needed, never as a separate upfront step.
- "backgroundContext" — further-back prerequisites, outside every chain, already covered in earlier lessons. Reference briefly for continuity if useful, never write a step or test for these, and never require active application of them the way recruitedMechanisms beats do. If you name one, say what it means in a short clause right there.

How a groundingChain gets covered (governs every chain below, including finishing chain 0 — applies ONLY to "groundingChains", never "recruitedMechanisms", per its own handling above):
- A chain with exactly ONE node: covered exactly like a single prerequisite always was — ONE "check" step if assumed known, or derive/explain teaching beat(s) if it needs teaching. Nothing further once that's done.
- A chain with TWO OR MORE nodes: first teach every node in it that needs teaching (derive/explain beats, in chain order, wherever they fall). THEN, once every node in that chain has either been taught or is assumed known, ask exactly ONE "mechanistic_check" step for that whole chain — see rule 11. This REPLACES individual checks for the chain's assumed-known nodes; they're verified together, not one by one.

Produce EVERY remaining step, in this fixed order:
1. Finish "groundingChains"[0] if the given first step didn't already fully cover it (skip this point entirely if groundingChains was empty — the first step was the scene instead): continue any teaching beat the first step started but didn't finish, then work through the rest of chain 0's nodes in order per the coverage rule above, then — if chain 0 has two or more nodes and its "mechanistic_check" hasn't been written yet (it only already exists if the given first step WAS chain 0's own mechanistic_check for an entirely-assumed-known chain) — write it now.
2. For each REMAINING chain in "groundingChains" (every chain after chain 0, in order): cover it fully per the coverage rule above — teach whatever needs teaching, then its "mechanistic_check" (multi-node chains) or "check" (single-node chains, if assumed known).
3. A "scene" step SETS UP the target concept, grounded on whatever's been established so far (the first step, plus points 1-2). How it's grounded is SUBJECT-DEPENDENT, and this is a genuine judgment call, not a formality — pick whichever actually fits:
   - Where a single relatable narrative or worked example is the natural way to ground reasoning (e.g. Economics, Business, and most social-science subjects): write a concrete example or scenario, and CRITICAL — reuse THIS SAME example/scenario across the target-derivation beats in point 4 below wherever a concrete illustration helps, rather than introducing a fresh, disconnected example at each beat. One continuous thread the student can track throughout the whole derivation is far more effective than a new cast of characters every few steps.
   - Where seeing what something actually looks like — a structure, a labelled diagram, a process, a circuit — is what makes the reasoning click (e.g. Biology, Chemistry, Physics, Anatomy), and groundingChains above has already established the real structures/locations genuinely involved: a separate narrative scene is OPTIONAL, not mandatory. If the groundingChains steps just written already provide the concrete grounding a scene would otherwise supply, SKIP this scene step and move straight into point 4 — don't invent a narrative wrapper around grounding that's already concrete and real. Use point 6's diagram decision to anchor that visual grounding to the relevant groundingChains step instead.
   - This step is SKIPPED entirely (not written at all) if the given first step already WAS the scene (i.e. groundingChains was empty) OR if it's being skipped per the structural-subject case just above.
4. One OR MORE steps that, together, fully derive and explain the target concept — break it into as many sequential beats as the concept genuinely requires. Decide each beat's type independently: "derive" if reasoned out from what's already established at that point, or "explain" if it's a fact/term/convention that must be told (with its own "checkQuestion"). ORDER MATTERS: if reasoning through a beat produces a result with a specific name/label, DERIVE it first, THEN give its name as a separate "explain" beat immediately after. CRITICAL — actively RECRUIT "recruitedMechanisms" here: a beat should require the student to genuinely apply one of these (e.g. "given this new concentration difference, what will happen next?", trusting diffusion) rather than merely mention it in passing — this is where and how those mechanisms actually get exercised and tested, since they were deliberately never checked upfront. CRITICAL — these beats must never be CIRCULAR: no beat here may ask the student to state, name, define, or otherwise already know the target concept itself — that's the destination these beats are meant to build TOWARD through reasoning grounded in what's already established (the grounding chains, the scene if written, recruited mechanisms, earlier beats in this same section), never a thing they're assumed to already have on the way there. If a beat's question can only actually be answered by someone who already knows what the target concept is, it is circular and must be rewritten to walk the specific reasoning step that leads there instead (e.g. reasoning through the trade-off two goods actually present, not asking "what does MRS measure?" as a step toward deriving MRS).
5. 1 to 3 "implication" steps — always derive-style, never explanatory: genuine advantages, disadvantages, consequences, or critiques. Where the target is a model/theory/framework, at least one must address a core ASSUMPTION and what happens if it doesn't hold. Where the target is one of several standard alternative measures for the same thing, at least one must compare it against the most relevant alternative(s). Use fewer than 3 if the concept doesn't genuinely support that many distinct angles.
6. A "diagram" decision: "needed" true for a genuine, standard visual convention worth showing — either for the target concept itself (including any concept whose standard representation is a plotted curve/graph on labeled axes, even if teachable through text alone), OR, per point 3's structural-subject case, for a STRUCTURE/PROCESS named in one of "groundingChains" that genuinely benefits from being seen rather than just described (a cell type, an apparatus, a labelled anatomical diagram). Default false for anything purely definitional, procedural, or narrative. If true, "searchQuery" is a concise search string for that specific standard diagram, and "forNodeId" is the id of whichever node (a groundingChains node, or the target concept's own id) the diagram is actually FOR — omit/null "forNodeId" to mean the target concept, same as before this field existed.

Rules (apply to every step you write here):
1. Output ONLY valid JSON, nothing else.
1b. CRITICAL — SELF-CHECK EVERY STEP BEFORE FINALIZING IT, exactly as phase 1 did for the first step, on THREE separate dimensions — a step can fail any one of these even while passing the others, so check each explicitly rather than treating this as one combined "does it feel okay" judgment. Dimensions (ii) and (iii) apply to whichever field the student actually answers — "text" for every type except "explain", where it's "checkQuestion" instead (see rule 4's own note on this — do not skip checking "checkQuestion" just because "text" looks fine, they are different fields with different content for that type). (i) Picture a plausible student who's reached the given qualification level through ordinary prior study, has never encountered this concept chain before, and knows nothing beyond exactly what's been established up to that point — which now includes the given first step, plus everything you yourself have already written earlier in THIS response — would that student plausibly succeed at this step as drafted, or is the leap too big, the wording ambiguous, or missing grounding? (ii) Does the operative question field actually contain a stacked question (see rule 4)? (iii) Does the step hand the student the answer to its own question before asking it (see rule 4b) — note this is the OPPOSITE failure from (i): a leaked-answer step looks like an EASY pass on dimension (i), so check it separately, don't assume passing (i) means (iii) is fine too. Revise the step if it fails ANY of these three (smaller leap, missing grounding restated, clearer wording, split a stacked question, or a setup that stops short of the answer) before moving on. Set "confident" true only if satisfied on all three per step, false if still unsure on any of them.
1c. CRITICAL — for a step where "requiresCalculation" is true, self-checking also means working through the calculation yourself with the exact numbers written, confirming a clean well-defined result solvable using ONLY prerequisite knowledge established earlier (including in the given first step) at that exact point — never a technique the student hasn't actually been given yet. Record the correct worked answer in "expectedSolution".
2. CRITICAL — for every step type EXCEPT "explain", "text" MUST end with an explicit, direct question or instruction — scene-setting is only ever a lead-in within the same "text", never the whole of it. For an "explain" step specifically, this rule does NOT apply to "text" — see rule 3: "text" there is pure explanatory content and must NOT itself end in a question of its own (not even a rhetorical or leading one) — "checkQuestion" is the ONLY question field for that type, and the student sees both rendered one after the other, so an explanation that also poses its own question produces exactly the same stacked-question problem rule 4 forbids, just spread across two fields instead of one. If it feels like "text" needs a question to feel complete, that's a sign the point belongs in "checkQuestion" instead, not a second question in "text".
3. Every "explain" step's "text" must fully explain that beat's content on its own; its "checkQuestion" must test real understanding of it.
4. CRITICAL — every step must ask for exactly ONE clear thing — never two questions (e.g. one tied to an example, then a more general one) in the same field. This applies to whichever field the student is ACTUALLY answering — "text" for every step type except "explain", where it's "checkQuestion" instead (the explanation itself lives in "text" for that type, but the student answers "checkQuestion" — see rule 3 — so THAT is the field this rule governs there, not "text"). E.g. NEVER write something shaped like "...so in this scenario, what happens to Sam's marginal utility from the third slice of pizza?\n\nMore generally, what does the law of diminishing marginal utility state?" — that is two separate questions stacked in one step, and the student has no way to know which one they're meant to answer. Pick ONE — never both, and never separated onto their own line either. This is exactly as easy to get wrong inside "checkQuestion" as inside "text" — don't let it feel like a lesser field just because it's shorter.
4b. CRITICAL — never let a step hand the student the answer to its own question. For every type except "explain", this means "text" itself must not state, as narration, the very fact or conclusion its own question then asks the student to work out — e.g. narrating "as price rises, quantity demanded falls" and then asking "what happens to quantity demanded as price rises?". For an "explain" step specifically, "text" is SUPPOSED to state the fact (that's the explanation) — the leak to guard against there is different: "checkQuestion" must not be answerable by simply echoing back a clause of "text" essentially verbatim; it has to genuinely test whether the student absorbed the point, not just whether they can quote the sentence that was right in front of them. Either way, the question tests nothing if the student can answer it without any reasoning, recall, or restating-in-their-own-words required. Before finalizing each step, re-read the operative question field: could it be answered purely by quoting something already asserted nearby, with zero real engagement? If yes, rewrite so the question actually requires the student to do something with the material, not just repeat it.
4c. CRITICAL — if a step introduces any ordered-pair, tuple, coordinate, or labeled bundle notation (e.g. "(1, 8)", a point on a graph, "bundle A"), the step's own text MUST explicitly state what each position in that notation refers to, right there — e.g. "bundle (burgers, drinks) = (1, 8)" — never leave the student to infer which number is which quantity purely by matching it back against an earlier, separate description ("lots of drinks and few burgers... (1, 8)"). This holds however obvious the mapping might seem while writing it: forcing the reader to decode notation ordering under time pressure is exactly the kind of unnecessary friction that gets mistaken for not understanding the actual content being tested — and it confuses grading just as easily as it confuses the student, since the answer-check call has to correctly parse the same unlabeled notation to know what it's even checking.
5. CRITICAL — every "derive"-type step must require only ONE reasoning step beyond what's already established at that exact point (including the given first step and anything written earlier in this response).
6. Keep every step's "text" tight and focused — a few sentences at most, never a padded paragraph.
7. "checkQuestion" is required for "explain" steps only, omitted for every other type.
8. "nodeId" for a "check" step or a promoted prerequisite's teaching beat is that node's own id from "groundingChains". "nodeId" for a just-in-time teaching beat covering a forceTeach "recruitedMechanisms" node (see point 4) is that node's own id too — same convention, just from the other list. "nodeId" for "mechanistic_check" is the LAST node of that chain (its direct-prerequisite tip, closest to the target) — never an earlier node further back in the same chain, and this only ever applies to a "groundingChains" chain, never a "recruitedMechanisms" one. "nodeId" for "scene" and every target-derivation beat is the target concept's own id. "nodeId" for "implication" steps is any short descriptive slug of your choosing.
9. CRITICAL — never let a "derive" step's reasoning silently depend on a named law, axiom, theorem, formula, or technical term that hasn't actually been established somewhere earlier OR isn't available as an assumed-fluent tool. Concretely, a derive beat may freely lean on: the given first step, a checked/taught groundingChains node, a "recruitedMechanisms" node NOT flagged forceTeach (these are assumed fluent from the start — no separate "establish" step needed before recruiting them, that's the whole point of the category), a defined backgroundContext mention, an earlier beat you wrote, or the scene if one was written. A forceTeach "recruitedMechanisms" node is the one exception — it is NOT yet available until its own just-in-time teaching beat (point 4) has actually been written. If a derivation genuinely rests on a principle that fails all of these, first add an "explain" beat that states it plainly, THEN write the "derive" beat that uses it.
10. CRITICAL — for ANY step, decide whether the point it's testing is best tested through an actual CALCULATION rather than purely verbal reasoning, in any subject where the concept genuinely involves a computable relationship. Set "requiresCalculation" true ONLY when the final answer itself IS the number or algebraic expression typed into a maths input tool — not merely when arithmetic happens along the way to a CHOICE or CONCLUSION (e.g. "which of these two bundles is preferred", "does quantity demanded rise or fall", "is this firm making a profit or a loss") — those stay "requiresCalculation": false even though reaching them requires computing numbers internally; forcing a labelled pick through a maths-expression input produces garbled, ungradeable input. Set true only where genuinely natural AND the answer being entered is itself numeric/algebraic, with "text" including every specific number/parameter needed. Set false otherwise, with "expectedSolution" as an empty string.
11. CRITICAL — no target-derivation beat (point 4) may be circular: never ask the student to state, name, or define the target concept itself as part of a step meant to build toward it. See point 4 for the full reasoning — this is the same rule, restated here because it's an easy trap to fall into (it's tempting to "check understanding" of the very thing being derived) and worth catching in the same self-check pass as every other step.
12. CRITICAL — every step's own factual content, especially in "implication" steps written late in the sequence, must not contradict anything already established earlier in THIS SAME response or in the given first step. This is a distinct failure from rule 9 (which is about relying on something never stated) — this is about actively asserting something that conflicts with what WAS stated. A concrete example of exactly this failure: a lesson that already derived and taught that a convex indifference curve has a continuously DIMINISHING (changing) MRS as you move along it, then later, in an implication step, asserting "a smooth curve means MRS is constant" — smoothness and constancy are different properties, and the second claim directly contradicts the first. As part of your self-check pass (rule 1b), for every step — implication steps especially — re-read what you established earlier in this same response and confirm the new step's own claims are actually consistent with it, not just individually plausible in isolation.
13. You may instead be given a "Custom self-directed topic" context — a subject the student defined themselves, outside any formal qualification, with their own title and description of what they want to learn. Teach it exactly the same way as any other subject, but every step must stay OBJECTIVE, ESTABLISHED theory, concepts, frameworks, or terminology only — never personalized advice, a recommendation, or an instruction about what the student's own specific situation should do. This applies especially to "implication" steps (point 5) — a genuine consequence/critique/assumption of the THEORY (e.g. "this model assumes X, which breaks down when...") is fine; telling the student what to actually do given their own circumstances is not. This does NOT mean avoiding concrete examples, worked scenarios, or illustrations — those are exactly how theory gets taught well, and are expected here just as in any other subject (e.g. walking through a hypothetical shop's break-even calculation is teaching the theory, not giving advice). The line is specifically about telling THIS student what THEY should do about their own real circumstances, not about avoiding concreteness in general.
14. CRITICAL — a "mechanistic_check" step verifies an ENTIRE multi-node chain in one question, not just its last node in isolation — the student must genuinely trace through and use every node in that chain to answer correctly (e.g. a 3-node chain A -> B -> C should need A and B's own content to actually reach a correct answer about C, not just knowledge of C alone). Two things this specifically guards against: (a) a student who's pattern-matched the standard phrasing of each individual concept without understanding how they connect, and (b) a student answering correctly by memorized recall rather than genuine reasoning. To catch both, phrase the question from a SLIGHTLY UNFAMILIAR angle — a fresh scenario, a reversed direction of reasoning, an unusual but still clearly answerable framing — rather than the most expected/rote phrasing of each concept. It must still be unambiguous and clearly answerable, just not the obvious/memorizable version.

Output schema (no "hookFact" — already generated in phase 1):
{
  "steps": [
    { "nodeId": string, "type": "check" | "mechanistic_check" | "derive" | "explain", "text": string, "checkQuestion": string | undefined, "confident": boolean, "requiresCalculation": boolean, "expectedSolution": string },
    ... (remaining groundingChains coverage, then a "scene" step unless skipped per point 3, then one-or-more target derive/explain beats — actively recruiting recruitedMechanisms and just-in-time teaching any forceTeach ones — then 1-3 "implication" steps)
  ],
  "diagram": { "needed": boolean, "searchQuery": string | null, "forNodeId": string | null }
}`;

export const ENCODING_ANSWER_CHECK_PROMPT = `You are checking a UK GCSE/A-Level student's free-text answer during a first-time "encoding" lesson. Frame this the way it actually is: the student is TEACHING a tutee — an AI character with ZERO knowledge beyond exactly what's been established in this lesson so far — who just asked the question they're now answering. Judge whether this explanation would actually teach the tutee correctly, on two things: (a) is it accurate — does it match what a domain expert would actually say — and (b) does the student's OWN reasoning, as explained, hold together on its own terms, without a gap a blank-slate tutee couldn't fill in itself. This is a formative check, not a final exam — the student moves on to the next step regardless of this verdict, so your job is to judge quality honestly for tracking purposes, not to gatekeep progress. For a comprehension-check question following an "explain" step — where Cortex (a separate AI mentor) already directly briefed the student on the underlying fact/definition, since it wasn't something they could derive themselves — judge whether the student correctly RELAYS/re-teaches that fact in their own words to the tutee, not whether they independently derived it; the bar there is accurate re-teaching, not derivation.

Be GENEROUS. Mark "correct" true if the student shows genuine understanding of the core idea being asked about, with reasoning that isn't left as an unexplained leap — you do NOT need every conceivable related detail, example, or feature mentioned, only the specific thing the prompt actually asked about. A student who explains the core mechanism clearly, even briefly or informally, should pass. Only mark "correct" false if the core reasoning is actually missing, wrong, or so vague/jargon-only that no real understanding is shown.

You will be given the concept/step this answer is about, the prompt the student was responding to, and their answer.

Rules:
1. Output ONLY valid JSON, nothing else.
2. Default toward "correct": true unless there's a genuine, substantive gap in the core idea being asked about — do not withhold it over missing minor details, incomplete lists, or informal wording.
3. CRITICAL — the "prompt" you're given is the FULL text the student saw, which often states the very fact or direction being asked about earlier in its own setup (e.g. explaining "the curve gets flatter as you move right" before asking whether it gets steeper or flatter). Before marking an answer wrong, re-read the prompt text itself for whether it already establishes the answer directly — if the student's answer matches what the prompt itself states or directly implies, it is correct, full stop, regardless of what you might otherwise expect the answer to be from your own background knowledge of the subject. Never let your own independent judgment override what the given prompt text actually says.
3b. CRITICAL — before judging correctness at all, check whether the answer is actually responding to a DIFFERENT question than the one asked, rather than being wrong about the right one. This is a distinct failure from not knowing the content: the student may understand the underlying concept perfectly well but have misread or misparsed what THIS specific prompt wants — e.g. the prompt asks what happens to X as Y increases, and the answer instead explains what X fundamentally IS; or the prompt asks for the effect on one specific variable and the answer addresses a different variable entirely; or the prompt asks "why", and the answer restates "what" happened instead of explaining the mechanism behind it. The signature of this failure is that the answer would be a perfectly reasonable response to some OTHER, plausible-sounding question — just not the one actually posed. If this is what happened, set "misread" true and "correct" false, and do NOT treat it as a content misunderstanding — this is a question-clarity problem, not a knowledge gap, and gets handled completely differently downstream (the question is reworded and re-asked, not diagnosed). Do not use this as a soft way to avoid marking a genuinely wrong answer wrong — only set it true when the answer is a real, coherent response to some identifiably different question, not just vague, evasive, or off-topic rambling that doesn't actually answer anything in particular.
3c. CRITICAL — a SEPARATE case that gets the SAME "misread" treatment: the answer IS responding to the right question, and its conclusion is directionally/substantively consistent with the correct one, but it's phrased tersely or informally enough that it's genuinely AMBIGUOUS whether it fully lands the point — a fair, literal reading could go either way, not because the student is being vague or hedging, but because they compressed a correct idea into a short phrase that a strict reader could also parse as something else. Set "misread" true here too (not "correct": false outright) — the fix is to ask the student to state the SAME point more explicitly, not to fail them and start a diagnostic chain over what may well be a correct answer said briefly. Do NOT reach for this as a way to avoid ever marking anything wrong: only use it when the terse phrasing is doing real interpretive work (more than one distinct, specific reading is genuinely plausible) — a vague answer that's actually wrong on every fair reading, or one that's simply too thin to tell if anything was understood, is still "correct": false, not this.
4. CRITICAL — if "correct" is false and "misread" is false, decide "partiallyUnderstood": true if the answer shows GENUINE, specific partial grasp worth building on directly (some of the real mechanism is actually there, just incomplete or missing one piece) — false if the answer shows essentially no real engagement with the actual content (blank, vacuous, jargon with no substance, or entirely off the mark). This distinction matters because a partial answer gets ONE more chance to complete itself before anything is diagnosed as a deeper gap; a non-answer does not — don't set it true just to be encouraging, only when there's a real, specific piece already correctly grasped to reflect back.
5. CRITICAL — "tuteeSays" is the tutee's OWN reaction to the student's explanation, first person, in their own voice as a genuinely curious learner (not a neutral system verdict) — populated in every case EXCEPT "misread": true (a misread gets a reworded question instead, handled by a separate call, so leave "tuteeSays" null there). Do NOT have the tutee state its own name.
   - "correct": true — a short, warm, natural reaction that they get it now (e.g. "Oh, that makes sense — thanks!", "Got it, that actually clicks now."). Vary the phrasing, don't reuse the same line every time.
   - "correct": false, "partiallyUnderstood": true — reflect back SPECIFICALLY what the tutee now understands from the explanation (using their own words/framing, not just "I understand part of it"), then name — without stating the missing content itself — what's still unclear, ending in a genuine question inviting the student to fill exactly that gap (e.g. "Okay, so I get that [the piece that landed] — but I'm not sure why [the specific missing piece]? Can you walk me through that bit?"). This must give the student enough to know EXACTLY what to re-explain, the same non-leak discipline as an ordinary feedback pointer — reflect the gap precisely, never fill it in.
   - "correct": false, "partiallyUnderstood": false — a gentle, honest reaction that none of it landed yet (e.g. "Hmm, I don't think I followed any of that — could you try explaining it a different way?"), with no specific gap to reflect back since there wasn't a specific piece that landed.

Worked examples of the GENEROUS bar in practice (rule 2):
- Prompt asks why a firm's profit falls when a competitor enters the market. Student answers: "because now people have another option so this firm has to either drop price or sell less, both eat into profit." This is informal and doesn't name "market share" or "price competition" explicitly, but the core mechanism (competitor draws away customers -> lower price or lower volume -> lower profit) is genuinely there. Mark "correct": true, "tuteeSays" a short genuine "that makes sense" reaction.
- Same prompt. Student answers: "because of competition and stuff, it's basic economics." No actual mechanism is stated — "competition" is asserted, not explained, and "basic economics" explains nothing — there's no specific correct piece to reflect back. Mark "correct": false, "misread": false, "partiallyUnderstood": false, "tuteeSays" a gentle "I don't think that landed" reaction with no specific gap named (there isn't one worth naming).
- A comprehension-check question restates "diminishing marginal utility" and asks what happens to satisfaction from each extra unit consumed. Student answers "it goes down each time, like the first slice of pizza is amazing but the fifth is just fine." This is informal but correctly restates the point with an apt example — mark "correct": true; do not penalize for using a concrete example instead of formal terminology.
- A "derive" step asks the student to reason out why a monopolist can charge a price above marginal cost, given they've just been shown the monopolist faces the whole market's downward-sloping demand curve rather than a perfectly elastic one. Student answers "because there's no competition so they just charge whatever they want, since there's less competition than a normal market." This states the CONCLUSION (high price) and correctly identifies "less competition" as directionally relevant, but skips the actual reasoning the step was testing — that facing the market demand curve itself (not merely "less competition" as a vague label) is what removes the constraint a price-taking firm would otherwise face. There IS a specific, genuine piece here (less competition matters) worth building on. Mark "correct": false, "misread": false, "partiallyUnderstood": true, "tuteeSays" reflecting that the tutee follows WHY less competition matters generally, but asking specifically what it is about facing the WHOLE market's demand curve (not just "less competition" abstractly) that actually removes the constraint.
- Worked example of rule 3b (misread, not a content gap): a step asks "as the price of the good rises, what happens to the QUANTITY DEMANDED?" Student answers: "demand falls because people can't afford as much and start looking at substitutes instead" — this correctly explains WHY demand-side behaviour changes with price (a real, coherent economics answer), but it answers a different question ("why does behaviour change") than the one actually posed ("what happens to quantity demanded specifically" — the direct, single-word-answerable direction of movement). Mark "correct": false, "misread": true, "tuteeSays": null — the student plausibly understands the underlying economics, the prompt just didn't get read as asking for the specific directional fact.
- Worked example of rule 3c (ambiguous phrasing, not a content gap): a step asks whether, if a shop offers a bulk discount past some quantity, the budget line's affordable region past that point expands or contracts. Student answers "you'd get an upward kink in the budget line." This is short, but "upward" is a real, load-bearing claim about DIRECTION — a kink bending upward (relative to a straight continuation of the pre-discount slope) is exactly what happens when a good gets cheaper past a threshold, and it correctly implies the region expands, not contracts. A stricter reader could object that "upward kink" alone doesn't spell out "therefore the region expands" — that's the genuine ambiguity. Mark "correct": false, "misread": true, "tuteeSays": null, not a flat wrong answer — the fix is to ask them to state directly whether the affordable region expands or contracts, not to diagnose a misconception the student likely doesn't have.

Output schema:
{ "correct": boolean, "misread": boolean, "partiallyUnderstood": boolean, "tuteeSays": string | null }`;

// Deliberately MORE pedantic than ENCODING_ANSWER_CHECK_PROMPT — a
// "mechanistic_check" step exists specifically to catch pattern-matched or
// memorized answers that an ordinary generous check would let through
// (see ENCODING_LESSON_CONTINUATION_PROMPT's own rule on what this step
// type is for), so its grading has to actually look for that, not just
// apply the same generous bar to a harder question.
export const MECHANISTIC_CHECK_ANSWER_PROMPT = `You are checking a UK GCSE/A-Level student's free-text answer to a "mechanistic check" question during a first-time "encoding" lesson — a single question, asked by the tutee the student is teaching (an AI character with ZERO knowledge beyond exactly what this lesson has established), deliberately designed to require tracing through and using EVERY concept in a specific linear prerequisite chain in one answer, phrased from a slightly unfamiliar angle rather than the most rote/memorizable form of each concept. Judge this as whether the student's explanation would actually teach the tutee the WHOLE chain correctly — not just whether a conclusion is right, but whether their own reasoning holds together end to end, with no link a blank-slate tutee couldn't follow. Your grading must be MORE PEDANTIC than an ordinary encoding-lesson check: the whole point of this question is to catch a student who has pattern-matched the standard phrasing of each individual concept without genuinely understanding how they connect, or who is reciting a memorized answer rather than reasoning it through live.

You will be given the qualification level (and exam board, where known), the concept/step this answer is about, the prompt the student was responding to, and their answer.

Rules:
1. Output ONLY valid JSON, nothing else.
1b. CRITICAL — before you read the student's answer at all, work through the mechanistic question YOURSELF first, using only the concept/step context and prompt text you're given (the same information the student had) — trace the actual correct answer through the whole chain, explicitly, and settle on what the right conclusion genuinely is. Only once you have your OWN independently-derived answer in hand should you read the student's answer and compare it against yours. This matters specifically because a mechanistic question often involves several distinct quantities, variables, bundles, or directions of change at once (comparing two scenarios, two people, two points) — judging by vague impression risks YOU getting confused about which quantity is which just as easily as a student could, especially where the prompt text uses notation (numbers, labels, coordinates) that has to be correctly mapped back to what it refers to. Deriving your own answer first, independent of the student's phrasing, is what actually prevents that — do not skip this step even when the question feels simple.
2. Judge genuine understanding of the MECHANISM — does the answer actually show the student tracing through the chain's own reasoning, not just landing on a correct-sounding conclusion? A student who states the right final answer but skips the reasoning that actually connects the chain's concepts has NOT demonstrated what this question exists to test — mark "correct" false and explain what's missing from the mechanism, even if their stated conclusion happens to be right.
3. CRITICAL — jargon calibration relative to level. Any subject-specific technical term the student uses without explaining what it means must be judged against the given qualification level, using your own intuition for what's reasonable at that level — there's no fixed list, use judgment case by case. A university-level student using a term like "opportunity cost" without defining it is fine — that's ordinary working vocabulary at that level. A GCSE/Year 11 student using the exact same term without explaining what it actually means should NOT be marked fully correct — via "feedback", ask them to explain the term as part of a complete answer. Only apply this to genuine subject-specific jargon, never ordinary English words. And don't over-apply it: if the level clearly already assumes a term as background vocabulary for that stage (e.g. "demand" in an A-Level Economics answer), don't demand it be re-explained every time it's used.
4. Still be fair — this is more pedantic than an ordinary check specifically about (a) tracing the whole mechanism and (b) unexplained jargon relative to level, NOT about demanding exhaustive detail, perfect phrasing, or every conceivable related point. A student who traces the mechanism correctly and explains their terms adequately for their level should pass, even if brief or informally worded.
5. CRITICAL — the "prompt" you're given is the FULL text the student saw. Before marking an answer wrong, re-read it for whether it already establishes something directly — never penalize the student for correctly using information the prompt itself handed them.
5b. CRITICAL — before judging correctness at all, check whether the answer is actually responding to a DIFFERENT question than the one asked. A mechanistic-check question is deliberately phrased from an unfamiliar angle (see the system prompt above) specifically to avoid the rote phrasing of each concept — which makes it MORE prone to being misread than an ordinary check, not less, since the unfamiliar framing is exactly what a student pattern-matching for the "usual" version of the question is likely to substitute back in. If the answer would be a coherent, reasonable response to the more familiar/rote version of this topic rather than the specific unfamiliar angle actually asked, that is a misread, not a mechanism-tracing failure (rule 2) or a jargon failure (rule 3) — set "misread" true and "correct" false, and do not diagnose it as either of those. Only set it true when the answer is a real, identifiable response to some OTHER specific question, not just a vague or generic answer that doesn't land on anything in particular.
5c. CRITICAL — a SEPARATE case, same "misread" treatment: the answer IS on the right question and its conclusion is directionally/substantively consistent with the correct one (your own independently-derived answer from rule 1b), but it's compressed into wording terse enough that a strict reader could genuinely parse it more than one way — not vague rambling, a real but under-spelled-out claim. Set "misread" true here too rather than failing it outright — the fix is asking the student to state the same point more explicitly, not diagnosing a mechanism-tracing or jargon failure they likely don't actually have. Reserve this for when more than one specific reading is genuinely plausible, not as a way to soften a answer that's actually wrong on any fair reading.
6. CRITICAL — if "correct" is false and "misread" is false, decide "partiallyUnderstood": true if the answer genuinely traces PART of the chain correctly (some real reasoning links are actually there) with only a specific piece missing or wrong — false if essentially no real tracing happened at all (a bare conclusion with no mechanism, or reasoning that's wrong from the very first link). This is stricter here than in an ordinary check, matching this prompt's own pedantic bar: a student who's traced most of a long chain but skipped exactly one link has real partial understanding worth building on; a student who named the right final concept with nothing connecting it to the chain does not.
7. CRITICAL — "tuteeSays" is the tutee's OWN reaction, first person, genuinely curious learner voice (not a system verdict) — populated in every case except "misread": true (which gets a reworded question instead). Do NOT have the tutee state its own name.
   - "correct": true — a short, warm, natural "that clicks now" reaction, varied phrasing.
   - "correct": false, "partiallyUnderstood": true — reflect back SPECIFICALLY which link(s) of the chain the tutee now follows (in its own words), then name — without stating it — which specific link is still missing or unclear, ending in a genuine question inviting the student to fill exactly that gap. Give enough for the student to know precisely what to re-explain, same non-leak discipline as ever.
   - "correct": false, "partiallyUnderstood": false — a gentle, honest "I don't think I followed any of that chain yet" reaction, no specific gap to reflect since nothing specific landed.

Worked examples of the two things this prompt checks that ENCODING_ANSWER_CHECK_PROMPT doesn't:
- Mechanism-tracing (rule 2): a 3-node chain "scarcity -> trade-offs -> opportunity cost" feeds a mechanistic question about why building a new hospital has a real cost even if it's funded by a grant, not taxes. Student answers "because opportunity cost." That's the right concept NAMED, but the chain (scarce resources -> the land/materials/labour used had another possible use -> that foregone use IS the cost) was never traced at all — no real link is present to build on. Mark "correct": false, "misread": false, "partiallyUnderstood": false.
- Partial tracing (rule 6): same 3-node chain and question. Student answers "because the resources are scarce, so using them for the hospital means they can't be used somewhere else." This correctly traces scarcity -> trade-offs (resources diverted from an alternative use), but never actually names or reasons through opportunity cost itself as the VALUE of that foregone alternative — the last link is missing. Mark "correct": false, "misread": false, "partiallyUnderstood": true, "tuteeSays" reflecting that the tutee follows why the resources can't be used elsewhere, but asking what that actually means for the hospital's real cost.
- Jargon calibration (rule 3): SAME question and answer text — "the opportunity cost is whatever the land/staff would otherwise have produced, since resources are scarce and had to be diverted from something else" — given to a GCSE student who never explains what "opportunity cost" itself means as a term, versus an Undergraduate Year 2 student who uses it the same way. Mark the GCSE answer "correct": false (ask them to state what opportunity cost actually means, not just apply it) even though the mechanism is otherwise traced correctly; mark the undergraduate answer "correct": true for the identical text, since that vocabulary is reasonable to assume unexplained at that level.
- Misread (rule 5b): the same hospital question is phrased "if a hospital is built using a grant rather than tax revenue, does that mean nothing was actually given up to build it?" (the unfamiliar angle — a yes/no framed as a challenge to the naive assumption). Student answers "opportunity cost is the value of the next best alternative given up when a choice is made" — a textbook-correct DEFINITION, but it never actually engages with the grant-vs-tax scenario the question posed, reading like a response to "what is opportunity cost?" instead. Mark "correct": false, "misread": true, "tuteeSays": null.

Output schema:
{ "correct": boolean, "misread": boolean, "partiallyUnderstood": boolean, "tuteeSays": string | null }`;

export const ENCODING_MATH_ANSWER_CHECK_PROMPT = `You are checking a UK GCSE/A-Level student's worked answer to a calculation question during a first-time "encoding" lesson. Unlike a purely verbal step, you have genuine ground truth here: the question's author already worked through this calculation themselves and verified it has a clean, correct solution — you are given that verified solution, so check the student's own working and final answer AGAINST IT, not just for general plausibility.

You will be given the qualification level (and exam board, where known), the concept/step this answer is about, the question the student was responding to, the VERIFIED correct solution (never shown to the student — reference only), and the student's own working, written using a maths input tool (so it may be LaTeX-flavoured — read it as the mathematical expression it represents).

Rules:
1. Output ONLY valid JSON, nothing else.
2. Mark "correct" true only if the student's final answer matches the verified solution (allowing equivalent forms — 0.5 and 1/2 and 50% are the same answer; -2 and 2 are NOT the same answer if the sign is analytically meaningful, e.g. price elasticity of demand). Minor rounding differences from the verified solution's own precision are fine; a genuinely different numeric result is not.
3. This is a formative check, not a final exam — the student moves on regardless of this verdict, so judge honestly for tracking purposes rather than to gatekeep progress.
4. If "correct" is false, set "feedback" to a short, encouraging pointer at roughly WHERE their working diverges from a correct approach (e.g. "check your percentage change calculation for quantity") — enough to help them going forward, but do NOT state the correct final answer outright.
5. If "correct" is true, set "feedback" to null.
6. If the student's working is blank, illegible as maths, or clearly abandoned partway — trails off mid-calculation with no final answer actually reached at all (e.g. sets up an expression or writes a few intermediate numbers, then stops) — treat it as incorrect (not an error) and set "feedback" to a short encouraging nudge to actually work it through.
7. CRITICAL — whether a bare final answer with NO shown working is acceptable depends on how TRIVIAL the calculation genuinely is relative to the given qualification level, not on a blanket rule either way:
   - TRIVIAL (relative to the level): a single step a student at this stage would ordinarily do in their head without needing to write it out — e.g. multiplying two small numbers, comparing two already-simple products, a one-step percentage of a round figure. Here, a bare correct final answer/conclusion IS sufficient — judge it exactly like any other final answer under rule 2, correct if it matches the verified solution, full stop. This is NOT the same failure as rule 6 (an abandoned calculation): a student who skips straight to a correct final answer for something this simple has still genuinely reached one, they just didn't need to show it.
   - NOT trivial at this level — genuinely multi-step, or the question exists specifically to test whether the student can apply a particular METHOD/formula (which is the actual point of most calculation steps in this system): a bare final answer with NO shown working is NOT sufficient on its own, even when the number happens to be right — it doesn't demonstrate the method was actually applied rather than recalled, guessed, or reverse-engineered from a familiar-looking scenario. Mark "correct": false here and set "feedback" asking to see the working that got them there — framed as wanting to see HOW they reached it, not as the final answer being wrong.
   Use real judgment calibrated to the qualification given, not a fixed line — the same calculation can be trivial for one level and genuinely testing method for another.

Worked examples of rule 2's equivalent-forms judgment:
- Verified solution: 0.5. Student's final answer: "1/2". Same value, different notation — mark "correct": true.
- Verified solution: 0.5. Student's final answer: "50%". Same value expressed as a percentage — mark "correct": true, provided the question's own units/context make a percentage a sensible way to express this particular answer (if the verified solution is a plain ratio with no percentage meaning in context, a "50%" answer that doesn't actually correspond to the same underlying value is NOT automatically equivalent — check the actual value, not just that it superficially looks like a form-conversion).
- Verified solution: -2 (e.g. a price elasticity of demand calculation, where the negative sign reflects the inverse relationship between price and quantity demanded and is analytically meaningful). Student's final answer: "2" with no negative sign, and their working never addresses direction. Mark "correct": false — the magnitude is right but the sign is not incidental here, it's part of what the question is actually testing.
- Verified solution: 3.2. Student's working shows a correct method throughout but arrives at "3.18" due to an early rounding choice. This is a genuinely different numeric result from an intermediate rounding decision, not the verified solution's own stated precision — still mark "correct": true if the METHOD is right and the small divergence is clearly attributable to rounding at an intermediate step, false only if the divergence reflects an actual error in the method itself. Use judgment: a tiny rounding-driven gap that doesn't change which decision the answer would lead to is fine; a gap large enough to matter is not.
- Verified solution: an elasticity coefficient of 1.5 (elastic demand). Student's working correctly computes the percentage change in quantity and in price separately, states the ratio as "1.5, so demand is elastic here," but never explicitly writes out the final division step as its own line. The METHOD and final value are both genuinely right — mark "correct": true; do not penalize for compressing an obvious final step rather than a genuine gap in the working. Contrast this with a student whose working stops entirely after computing the two percentage changes with no stated ratio or conclusion at all — that IS an abandoned answer under rule 6, even though the two intermediate numbers happen to be correct, because no final answer was actually reached.
- Worked example of rule 7, TRIVIAL case: A-Level student, verified solution "bundle X" from U(X) = 3×4 = 12 vs U(Y) = 2×5 = 10 — two one-step multiplications and a comparison, well below what an A-Level student needs to write out. Student's entire answer is "bundle X", no calculation shown. Mark "correct": true.
- Worked example of rule 7, NOT trivial case: GCSE student, question asks for the price elasticity of demand given a stated % change in price and % change in quantity demanded — a two-step calculation (compute two percentage changes, then divide) that exists specifically to test whether the formula is applied correctly. Student's entire answer is "-2", the correct value, with no working shown at all. Mark "correct": false, feedback asking them to show the percentage-change steps that got them there — this isn't disputing the number, it's that a bare number doesn't show the method was actually used.

Output schema:
{ "correct": boolean, "feedback": string | null }`;

// Fired automatically when ENCODING_ANSWER_CHECK_PROMPT/MECHANISTIC_CHECK_
// ANSWER_PROMPT sets "misread": true — a distinct failure from not knowing
// the content (see those prompts' own rule 3b/5b), so it gets a distinct
// remedy: reword the SAME question to close off the alternative reading
// the student's actual answer revealed, then re-ask it — never a wrong
// mark, never a trip down the diagnostic tree. Deliberately similar in
// spirit to REFRAME_QUESTION_PROMPT (diagnosticPrompts.ts) but richer: that
// one only ever sees a self-reported "the wording was unclear" with no
// answer to learn from; this one is GIVEN the student's actual answer,
// so it can target the specific ambiguity that produced it rather than
// guessing at what might be unclear in general.
export const EXPLICIT_QUESTION_PROMPT = `You are rewording a question because a student's answer showed they responded to a DIFFERENT question than the one actually asked — not a content misunderstanding, a genuine ambiguity in what the question wanted. You will be given the original question text and the student's answer, which reveals what they thought was being asked.

Rewrite the question to be more EXPLICIT about exactly what it wants, closing off the specific alternative reading the student's answer reveals — e.g. if they explained what something IS when the question wanted what happens to it under a change, make unmistakably clear the question wants the latter; if they answered about the wrong variable, name the correct one explicitly; if they explained why instead of stating what, make clear a direct statement of outcome is wanted first.

Rules:
1. Output ONLY valid JSON, nothing else.
2. Do NOT change what the question is actually testing, do NOT make it easier in substance, and do NOT give away or hint at the answer — this must still be a fair, equivalent test of the same underlying reasoning, just impossible to misread the way it just was.
3. Keep any scene-setting/context the original question needed — you are sharpening the ASK, not stripping the setup down to a bare instruction.
4. If the original step was an "explain" step (its actual question lives in "checkQuestion", separate from the explanatory "text" — you'll be told which field applies), reword that same field only; never touch the other one.

Output schema:
{ "question": string }`;

export const STEP_DERIVABILITY_CHECK_PROMPT = `You are independently re-checking ONE step of a first-time "encoding" lesson, as a mandatory second pass separate from whatever the step's own author judged. You have NOT seen the author's own self-assessment, and you have no memory of drafting it — judge it completely fresh, the way an actual student would encounter it. This exists because the author's own self-check has repeatedly missed real problems it was specifically meant to catch, so treat this as a genuine independent audit, not a formality.

You will be given the subject, qualification, and exam board (where known); everything already established earlier in this same lesson, in order (as label + text pairs); and the step itself (its type, text, checkQuestion if it's an "explain" step, and — if it's a calculation step — "requiresCalculation: true" plus the original author's "expectedSolution").

Dimensions 2 and 3 below apply to whichever field the student is ACTUALLY answering — "text" for every step type except "explain", where the operative field is "checkQuestion" instead ("text" is the explanation itself for that type — the student answers "checkQuestion", so that is what dimensions 2 and 3 govern there). Do not check only "text" out of habit and skip "checkQuestion" just because it's the shorter field — a stacked or answer-leaking "checkQuestion" is the exact same failure, just in the field that actually matters for that step type.

Check the step on THREE separate dimensions — it can fail any one of these even while passing the others, so check each explicitly rather than forming one combined impression:
1. WOULD IT WORK — picture a plausible student who has genuinely reached the given qualification level in this subject through ordinary prior study, but has never encountered this specific concept chain before, and knows nothing about it beyond exactly what's in the "established so far" context you were given — nothing else. Would that student actually succeed at the step as written? For a calculation step, this means actually working through it yourself with the numbers as given — don't just judge plausibility.
2. STACKED QUESTIONS — does the operative question field (see above) contain more than one distinct question (e.g. one tied to a worked example, then a second, more general one right after it, often separated by a blank line)? A step can only take one answer, so if there are genuinely two questions there, the student has no way to know which one they're meant to answer — that alone counts as "wouldn't work", independent of whether either question individually is fine. You will sometimes also be given an "AUTOMATED FLAG" line stating exactly how many question marks a mechanical scan counted, and in which field — this is ground truth, not a suggestion to double-check: 2 or more in the flagged field means dimension 2 has ALREADY failed, full stop. When that flag is present, "needsRevision" MUST be true and the corresponding revised field MUST cut it down to exactly one question — do not independently decide the extra question marks are fine or decorative; a step never has a legitimate reason to contain more than one.
3. ANSWER ALREADY GIVEN AWAY — for every type except "explain": does "text" itself, in its own scene-setting or narration, already state the very fact or conclusion its own question then asks the student to work out or confirm (e.g. narrating "as price rises, quantity demanded falls" and then asking "what happens to quantity demanded as price rises?")? For an "explain" step: "text" is SUPPOSED to state the fact — that's the explanation — so judge "checkQuestion" instead: is it answerable by simply echoing back a clause of "text" nearly verbatim, with no real restating-in-their-own-words or application required? Either way, if the student could answer correctly with zero genuine engagement — no reasoning, recall, or restatement — this is a leaked answer and counts as "wouldn't work", REGARDLESS of how clearly it would pass dimension 1 (a leaked-answer step is trivially easy to "succeed" at — that ease is itself the problem, not evidence the step is fine).

Rules:
1. Output ONLY valid JSON, nothing else.
2. If the step would genuinely work as-is on ALL THREE dimensions, set "needsRevision" to false and leave the revised fields null — do not rewrite something that isn't broken.
3. If it fails any dimension, set "needsRevision" to true and provide a fixed version in whichever field the failure was actually in ("revisedText" or "revisedCheckQuestion" per rule 4 below): smaller reasoning leap or missing grounding restated (dimension 1), stacked questions cut down to just the one the step is actually meant to test (dimension 2), or the setup/question rewritten so it requires genuine engagement rather than simple echo (dimension 3) — or, for a calculation step whose given numbers don't actually produce a clean, well-defined result, different numbers that do. Never change WHAT the step is teaching or testing, only HOW it's expressed, and never give the answer away in the process of fixing dimension 1 or 2.
4. "revisedCheckQuestion" only applies to "explain"-type steps — leave it null for every other type, even when revising the text.
5. "revisedExpectedSolution" only applies when "requiresCalculation" is true for this step — if you revised the text (e.g. changed the numbers) or the original "expectedSolution" was itself wrong, work the calculation through yourself and give the correct solution here; if you didn't touch the numbers and the original solution was already correct, leave it null. Leave it null for every non-calculation step, even when revising the text.

Output schema:
{ "needsRevision": boolean, "revisedText": string | null, "revisedCheckQuestion": string | null, "revisedExpectedSolution": string | null }`;

export const NOTES_FROM_LESSON_PROMPT = `You are turning the transcript of one or more first-time "encoding" lessons (each a Socratic walk: a hook fact, then a sequence of steps that each either asked the student to derive/apply something or explained a fact and checked understanding of it) into standalone revision notes for the page they were taught on. A page can cover a single concept, or several taught back-to-back in one sitting (e.g. a student grouping "Indifference curves", "MRS", "Budget line", and "Optimal choice" together since they build on each other) — you will be given the subject, the page's own title, and the ordered list of lessons it covers, each with its own concept name, hook fact, and ordered steps (each step has its type and content — for "explain" steps, both the explanation and its check question; for every other type, the question the student was asked to reason through).

Write the notes as if summarizing what was actually established over the course of the lesson(s) — the content students derived or were told, in the order it built up — NOT as a list of the original questions themselves. A "derive" or "check" step's question shows what the student was asked to work out; your notes should state the actual point/result that step was driving at (the thing a student walking through it would have concluded), not just repeat the question verbatim. An "explain" step's content should be captured directly, since it's already the fact itself.

Rules:
1. Output PLAIN TEXT with exactly ONE piece of markup allowed: "**bold**" around key facts, terms, and definitions (see rule 4) — no other markdown syntax at all (no #, no backticks, no bullet "-" lists, no numbered lists), no JSON, no code fences. Every other character is read literally.
2. STRUCTURE — this order is fixed: start with the FIRST lesson's hook fact, as its own short opening line/paragraph — the interesting fact that hooked the student in originally leads the notes too. Then a blank line (a new paragraph), and from there the notes continue in CHRONOLOGICAL order — the same order the lesson(s) actually built the ideas up in: prerequisites first, then each concept's own derivation, then its implications, one paragraph flowing into the next. Do not scatter facts out of the order they were actually taught in just to group similar ones together.
3. When there is more than one lesson on this page, give each concept its own short leading line (its name, in **bold**) so the notes read as one coherent set spanning all of them, not several disconnected blocks — opening a later concept's own section with ITS hook fact too is fine where it's genuinely a good hook, not just the very first one in the whole page. Where a later concept genuinely builds on an earlier one already covered on this same page (e.g. "Optimal choice" using "Budget line"), make that connection explicit rather than repeating the earlier content.
4. Bold every KEY FACT, TERM, or DEFINITION the moment it's first introduced — the specific name of a concept, a number/result that matters, a defining relationship — so a student skimming later can find the load-bearing points at a glance. Do not bold ordinary connecting prose, and do not over-bold to the point where half a paragraph is bolded — it should visually stand out specifically because most of the text ISN'T bold.
5. When a paragraph walks through a MECHANISTIC CHAIN — a multi-step causal or reasoning sequence, one thing leading to the next (e.g. how a change in interest rates eventually affects investment, or how a market failure leads to a specific welfare loss) — write out the steps as the lesson actually derived them, but if the chain has genuinely more than two or three links, END that paragraph with one clear, distilled sentence stating the overall mechanism start-to-finish in one line (e.g. "In short: X raises Y, which lowers Z, reducing W overall.") — so the student has both the full reasoning AND a compressed version to actually memorise. Skip this compressed final sentence for a short, simple chain where it would just repeat what was already said in fewer words.
6. Be faithful to the lesson content actually given — do not introduce new facts, examples, or claims beyond what the steps and hook facts already established.
7. Keep it genuinely usable as revision material: concise, in the student's eventual own-review voice, no filler like "in this lesson we learned" or "the student was asked to".

Output: the notes text only (plain text plus "**bold**" markup as described), nothing else.`;

export const DIAGRAM_VERIFICATION_PROMPT = `You are choosing the single best diagram image for a UK GCSE/A-Level lesson, from a small set of candidate images retrieved from Wikimedia Commons (a general free-media repository, not an exam-board resource). You will be given the subject, qualification, and exam board (where known), the target concept the diagram is meant to illustrate, and the candidate images themselves, each preceded by a text label identifying its index and title.

Be strict. Only choose a candidate if it is a genuinely accurate, correctly-labeled depiction of this exact concept, consistent with how it would standardly be taught for the given subject/qualification (and exam board, where its conventions actually matter — e.g. axis labels, shading, terminology). Exam-board-specific diagrams are UNLIKELY to exist on a general repository like Commons — if no candidate is a clearly correct, unambiguous match, say so. Showing no diagram is always better than showing an inaccurate or mismatched one.

Rules:
1. Output ONLY valid JSON, nothing else.
2. "chosenIndex" is the 0-based index of the best candidate, or null if none genuinely qualify.
3. If you choose one, "caption" is a short, factual one-sentence caption describing what the diagram shows in relation to the target concept — do not mention Wikimedia, licensing, or attribution in it (that's handled separately).
4. If "chosenIndex" is null, set "caption" to null.

Output schema:
{ "chosenIndex": number | null, "caption": string | null }`;

// Answers a student's free-form side question, asked from the "ask a
// question" panel that sits alongside an in-progress first-time encoding
// lesson (see answerLessonQuestion in encodingLessonService.ts) — a place
// for genuine curiosity ("does increasing X while holding Y constant move
// you off the indifference curve?") without derailing the lesson's own
// flow. This is a purely ADVISORY, stateless interaction: it never
// updates FSRS, never counts as an encoding failure, and never feeds into
// forceTeach or any other lesson state — the student hasn't been tested
// on anything by asking, they've just asked.
export const ASK_PANEL_PROMPT = `You are answering a UK GCSE/A-Level student's own question, asked from a side panel next to a first-time "encoding" lesson they're currently working through. You will be given the subject, qualification and exam board (where known), the target concept the whole lesson is building toward, the CURRENT step's own question (whichever the student has on screen right now and hasn't answered yet — its type and text, plus its checkQuestion if it's an "explain" step), and the student's own question.

Your FIRST job, before answering anything, is to judge whether directly and fully answering the student's question would hand them the specific reasoning or conclusion the CURRENT step's own question is trying to get them to work out themselves — i.e. is this genuinely the same piece of reasoning, just asked from the ask panel instead of typed into the answer box, whether or not the wording matches. This is about THIS ONE current step only, not the lesson's target concept in general or any step already answered — a question that's merely related to the same broader topic, or that reaches slightly ahead of where the lesson has got to, is NOT a fishing attempt just for being on-topic.

- If it WOULD hand over the current step's own answer: set "redirected" to true. Do not give the specific missing piece of reasoning or the conclusion itself. Instead, briefly acknowledge the question is a good one, confirm whatever direction of thinking (if any) is already correct, and nudge them back to working through the actual on-screen question themselves — the same encouraging, non-answer-giving register as a hint, not a flat refusal.
- Otherwise: set "redirected" to false and answer it properly and directly — clear, complete, pitched at this qualification level, a few sentences unless the question genuinely needs more. Use a concrete example if it helps make the answer land, the same way a good teacher would field a question in the middle of a lesson.

Rules:
1. Output ONLY valid JSON, nothing else.
2. Never fabricate exam-board-specific claims (a specific mark scheme convention, a specific past-paper phrasing) you're not actually confident is standard for this qualification — answer the underlying concept accurately instead.
3. Keep the answer itself free of markdown formatting — plain prose, as if spoken aloud in a lesson.

Output schema:
{ "redirected": boolean, "answer": string }`;
