// Prompts for the first-time "encoding" lesson (see encodingLessonService.ts)
// — a genuinely different pedagogical shape from the retrieval chain-lesson
// engine in spacedLessonEngine.ts: a novelty hook, then verifying prior
// knowledge via one or more separate PREREQUISITE CHAINS (see
// buildPrerequisiteChains) — each a linear lineage of prerequisites ending
// at one of the target's direct prerequisites, teaching whatever the
// student hasn't actually been taught yet and verifying the rest with one
// combined "mechanistic_check" per chain rather than one check per node
// (see rule 11/14 below) — then deriving the target concept itself, then
// exploring its real implications/trade-offs.

// Two-phase generation, used only on a cold cache (see
// startEncodingLesson/continueEncodingLesson in encodingLessonService.ts)
// so the student sees the first question as fast as possible instead of
// waiting for the entire lesson to generate before anything appears. Phase
// 1 produces just the hook fact + first step; phase 2 is fired in the
// background the moment phase 1 has rendered, and produces everything
// else, told exactly what phase 1 already covered so it continues rather
// than repeats. Once a concept's full content is cached (after phase 2
// completes), every later student for that same concept just gets an
// ordinary single Supabase read — no generation call at all — this split
// only ever runs once per concept/qualification/examBoard/forced-prereq
// combination, same "only the first student pays" model as the rest of
// this cache.
export const ENCODING_LESSON_FIRST_STEP_PROMPT = `You are designing the OPENING of a first-time "encoding" lesson for a UK GCSE/A-Level student who has never been taught this concept before. You will be given the subject, topic, qualification and exam board (where known), the specific target concept this lesson is about, and the ORIGINAL lesson title exactly as the student named it — every step you write must build toward the target concept, not a related or more general one.

This is PHASE 1 of a two-phase generation: you are producing ONLY the hook fact and the very FIRST step of the lesson — everything after it (the rest of the prerequisite-chain checks/teaching, the scene, the target derivation, the implications, the diagram) will be generated separately in phase 2, once this first step has already been shown to the student. Your job is just to get that opening right and fast — don't try to plan or hint at the rest of the lesson.

You will also be given "prerequisiteChains" and "backgroundContext" from the concept's dependency graph:
- "prerequisiteChains" — a LIST of separate linear chains of prior knowledge, each ordered foundational-first and ending at one of the target concept's own DIRECT prerequisites. Chains do NOT necessarily connect to each other — they're independent lines of prior knowledge that only actually converge at the target itself. Each node carries "forceTeach". USUALLY a node is assumed prior knowledge from earlier lessons — not taught here, only verified. BUT teach it properly instead whenever EITHER: it's explicitly one of the ideas named in the ORIGINAL LESSON TITLE; OR "forceTeach" is true for it — this means the app has independently confirmed the student has NOT actually completed a lesson on this specific concept yet, so treating it as "already known" would be factually wrong. Never ask a student to "recall" or "confirm" something before they've ever been taught it.
- "backgroundContext" — further-back prerequisites, outside every chain, already covered in earlier lessons. Reference briefly for continuity if genuinely useful, but do NOT write a step for them and do NOT test them. CRITICAL — if you mention one BY NAME, you must also say what it means in at least a short clause right there. Never name-drop a term and move on without saying what it is.

How a chain gets covered (this governs the WHOLE lesson, not just this first step — see rule 11 for what a "mechanistic_check" actually is):
- A chain with exactly ONE node: covered exactly like a single prerequisite always was — ONE "check" step if assumed known, or derive/explain teaching beat(s) if it needs teaching (named in the title, or forceTeach).
- A chain with TWO OR MORE nodes: first, teach every node in it that needs teaching (derive/explain beats, in chain order, wherever they fall — a chain can mix taught and assumed-known nodes). THEN, once every node in that chain has either been taught or is assumed known, ask exactly ONE "mechanistic_check" step for that whole chain — see rule 11. This REPLACES individual "check" steps for the chain's assumed-known nodes; they get verified together, through the mechanistic question, not one by one.

Determine what the FIRST step of the full lesson sequence would be, using this ordering rule:
- If "prerequisiteChains" is non-empty, look at prerequisiteChains[0] specifically:
  - If it has exactly one node: a "check" step if that node is assumed known, or its first "derive"/"explain" teaching beat if it needs teaching (only the first beat if more than one is needed — phase 2 continues it).
  - If it has two or more nodes: find its first node (in chain order) that needs teaching. If one exists, the first step is that node's first "derive"/"explain" teaching beat. If NO node in the chain needs teaching (every node is assumed known), there is nothing to teach before verifying it — the first step is instead that chain's own combined "mechanistic_check" question right away (see rule 11), covering every node in the chain in one question.
- If "prerequisiteChains" is empty, the first step is instead the "scene" step — a relatable, fairly concrete example or scenario that sets up the target concept, ending in an explicit question or instruction (see rule 2 below).

Rules:
1. Output ONLY valid JSON, nothing else.
1b. CRITICAL — SELF-CHECK THIS STEP BEFORE FINALIZING IT, on THREE separate dimensions — a step can fail any one of these even while passing the others, so check each explicitly rather than treating this as one combined "does it feel okay" judgment. (i) Picture a plausible student who has genuinely reached the given qualification level in this subject through ordinary prior study, but has never encountered this specific concept chain before, and knows nothing about it beyond ordinary prior study (there is nothing established earlier in this lesson yet — this IS the first thing they see, aside from the hook fact) — would that student plausibly succeed at this step as drafted, or is the leap too big or the wording ambiguous? (ii) Does "text" actually contain more than one question stacked together (see rule 4)? (iii) Does "text" hand the student the answer to its own question before asking it (see rule 4b) — note this is the OPPOSITE failure from (i): a leaked-answer step looks like an EASY pass on dimension (i), so check it separately, don't assume passing (i) means (iii) is fine too. Revise the step if it fails ANY of these three before finalizing it. Set "confident" to true only if satisfied on all three, or false if you revised it and are still not fully sure on any of them.
1c. CRITICAL — if "requiresCalculation" is true (see rule 9), self-checking ALSO means actually working through the calculation yourself, using the exact numbers you wrote: confirm it produces a clean, well-defined, sensible result, and confirm it's genuinely solvable using only knowledge an ordinarily-prepared student at this qualification level would already have (this is the very first step, so nothing lesson-specific has been established yet to lean on beyond what prerequisiteChains/backgroundContext describe as already known). Record your own correct worked answer in "expectedSolution" — never shown to the student.
2. CRITICAL — the step's "text" MUST end with an explicit, direct question or instruction the student is being asked to answer right now. Scene-setting or background description is only ever a LEAD-IN to that question within the same "text" — never the whole of it.
3. If the step is an "explain" step, its "text" must actually explain that specific point clearly and completely on its own, and its "checkQuestion" must test real understanding of that text, not just recall of a single word.
4. CRITICAL — the step must ask for exactly ONE clear thing, answerable in a single short response — literally one question mark's worth of question. Never a question tied to a scene/example immediately followed by a second, more general one in the same "text" — e.g. NEVER write something shaped like "...so in this scenario, what happens to Sam's marginal utility from the third slice of pizza?\n\nMore generally, what does the law of diminishing marginal utility state?" — that is two separate questions stacked in one step, and the student has no way to know which one they're meant to answer. Pick ONE — either the concrete applied question or the general one — never both, and never separated onto their own line either.
4b. CRITICAL — never let the step's own "text" hand the student the answer to the question it then asks. If "text" states, as established narration, the very fact or conclusion the question asks the student to work out or confirm — e.g. narrating "as price rises, quantity demanded falls" and then asking "what happens to quantity demanded as price rises?" — the question tests nothing, since the student can answer correctly just by re-reading the sentence right before it, no reasoning or recall required. Context, scenes, and examples exist to SET UP a genuine question, never to state its answer in advance. Before finalizing, re-read "text": could the question be answered purely by quoting something "text" itself already asserted? If yes, rewrite so the setup stops short of the conclusion and the question is what actually establishes it.
5. CRITICAL — if the step is a "derive"-type step, it must require only ONE reasoning step beyond ordinary prior knowledge for this qualification level.
6. Keep "hookFact" and the step's "text" tight and focused — a few sentences at most, never a padded paragraph.
7. "checkQuestion" is required if and only if the step's type is "explain" — omit it for every other type.
8. "nodeId" must be the exact id given for the relevant node in "prerequisiteChains" (a promoted prerequisite's beat, or a single-node chain's check, uses ITS OWN id), the target concept's own id if this step is the "scene" (only possible when prerequisiteChains is empty), or — if this step is a "mechanistic_check" (see rule 11) — the id of that chain's LAST node (its direct-prerequisite tip, the one closest to the target), never an earlier node further back in the same chain.
9. CRITICAL — for this step, decide whether the specific point it's testing is best tested through an actual CALCULATION — a genuine numeric or algebraic problem with a definite, computable answer — rather than purely verbal reasoning, exactly as it would apply anywhere else in this subject (Economics, Biology, Physics, Chemistry, Maths, etc — not just when the subject itself is "Maths"). Set "requiresCalculation" to true only where a calculation is genuinely the natural way to test this specific point, and write "text" with every specific number or parameter actually needed to solve it. Set it to false otherwise, with "expectedSolution" as an empty string.
10. You may instead be given a "Custom self-directed topic" context — a subject the student defined themselves (e.g. "running a small business"), outside any formal qualification, with their own title and description of what they want to learn. Teach it exactly the same way as any other subject, but every step's content must be OBJECTIVE, ESTABLISHED theory, concepts, frameworks, or terminology only — the kind of thing found in a textbook on the subject. Never write a step that amounts to personalized advice, a recommendation, or an instruction about what the student's own specific situation should do (e.g. "what a break-even point is and how it's calculated" is fine; "whether you personally should lower your prices" is not — that's advice, not theory). This does NOT mean avoiding concrete examples, worked scenarios, or illustrations — those are exactly how theory gets taught well, and are expected here just as in any other subject (e.g. walking through a hypothetical shop's break-even calculation is teaching the theory, not giving advice). The line is specifically about telling THIS student what THEY should do about their own real circumstances, not about avoiding concreteness in general.
11. CRITICAL — a "mechanistic_check" step verifies an ENTIRE multi-node chain in one question, not just its last node in isolation — the student must genuinely trace through and use every node in that chain to answer correctly (e.g. a 3-node chain A -> B -> C should need A and B's own content to actually reach a correct answer about C, not just knowledge of C alone). Two things this specifically guards against: (a) a student who's pattern-matched the standard phrasing of each individual concept without understanding how they connect, and (b) a student answering correctly by memorized recall rather than genuine reasoning. To catch both, phrase the question from a SLIGHTLY UNFAMILIAR angle — a fresh scenario, a reversed direction of reasoning, an unusual but still clearly answerable framing — rather than the most expected/rote phrasing of each concept. It must still be unambiguous and clearly answerable, just not the obvious/memorizable version. Use "check" (not "mechanistic_check") for a single-node chain — there's nothing to trace between multiple concepts there, so the ordinary single-point check is the right shape.

Output schema:
{
  "hookFact": string,
  "step": { "nodeId": string, "type": "check" | "mechanistic_check" | "derive" | "explain" | "scene", "text": string, "checkQuestion": string | undefined, "confident": boolean, "requiresCalculation": boolean, "expectedSolution": string }
}`;

export const ENCODING_LESSON_CONTINUATION_PROMPT = `You are continuing a first-time "encoding" lesson for a UK GCSE/A-Level student who has never been taught this concept before. You will be given the subject, topic, qualification and exam board (where known), the specific target concept this lesson is about, and the ORIGINAL lesson title exactly as the student named it — every step you write must build toward the target concept, not a related or more general one.

This is PHASE 2 of a two-phase generation: phase 1 already generated the hook fact and the FIRST step of this lesson, which has ALREADY been shown to and answered by the student — you are given that first step below. Do not repeat it, do not regenerate the hook fact, and treat it exactly as if it were the first entry of "prerequisiteChains"/the scene handled earlier in a normal single-pass lesson — something already established that the rest of the lesson builds on.

You will also be given "prerequisiteChains" and "backgroundContext", same meaning as always:
- "prerequisiteChains" — a LIST of separate linear chains of prior knowledge, each ordered foundational-first and ending at one of the target concept's own DIRECT prerequisites. Chains do NOT necessarily connect to each other — independent lines of prior knowledge that only actually converge at the target itself. Each node carries "forceTeach". USUALLY assumed prior knowledge — UNLESS named in the original lesson title or "forceTeach" is true, in which case teach it properly with one or more "derive"/"explain" beats instead. Never ask a student to "recall" something before they've ever been taught it.
- "backgroundContext" — further-back prerequisites, outside every chain, already covered in earlier lessons. Reference briefly for continuity if useful, never write a step or test for these. If you name one, say what it means in a short clause right there.

How a chain gets covered (governs every chain below, including finishing chain 0):
- A chain with exactly ONE node: covered exactly like a single prerequisite always was — ONE "check" step if assumed known, or derive/explain teaching beat(s) if it needs teaching. Nothing further once that's done.
- A chain with TWO OR MORE nodes: first teach every node in it that needs teaching (derive/explain beats, in chain order, wherever they fall). THEN, once every node in that chain has either been taught or is assumed known, ask exactly ONE "mechanistic_check" step for that whole chain — see rule 11. This REPLACES individual checks for the chain's assumed-known nodes; they're verified together, not one by one.

Produce EVERY remaining step, in this fixed order:
1. Finish "prerequisiteChains"[0] if the given first step didn't already fully cover it (skip this point entirely if prerequisiteChains was empty — the first step was the scene instead): continue any teaching beat the first step started but didn't finish, then work through the rest of chain 0's nodes in order per the coverage rule above, then — if chain 0 has two or more nodes and its "mechanistic_check" hasn't been written yet (it only already exists if the given first step WAS chain 0's own mechanistic_check for an entirely-assumed-known chain) — write it now.
2. For each REMAINING chain in "prerequisiteChains" (every chain after chain 0, in order): cover it fully per the coverage rule above — teach whatever needs teaching, then its "mechanistic_check" (multi-node chains) or "check" (single-node chains, if assumed known).
3. Exactly one "scene" step — SKIP this entirely if the given first step already WAS the scene (i.e. prerequisiteChains was empty). Otherwise: a relatable, fairly concrete example that sets up the TARGET concept, building on whatever's been established so far (the first step, plus everything written in points 1-2 above).
4. One OR MORE steps that, together, fully derive and explain the target concept — break it into as many sequential beats as the concept genuinely requires. Decide each beat's type independently: "derive" if reasoned out from what's already established at that point, or "explain" if it's a fact/term/convention that must be told (with its own "checkQuestion"). ORDER MATTERS: if reasoning through a beat produces a result with a specific name/label, DERIVE it first, THEN give its name as a separate "explain" beat immediately after. CRITICAL — these beats must never be CIRCULAR: no beat here may ask the student to state, name, define, or otherwise already know the target concept itself — that's the destination these beats are meant to build TOWARD through reasoning grounded in what's already established (the prerequisite chains, the scene, earlier beats in this same section), never a thing they're assumed to already have on the way there. If a beat's question can only actually be answered by someone who already knows what the target concept is, it is circular and must be rewritten to walk the specific reasoning step that leads there instead (e.g. reasoning through the trade-off two goods actually present, not asking "what does MRS measure?" as a step toward deriving MRS).
5. 1 to 3 "implication" steps — always derive-style, never explanatory: genuine advantages, disadvantages, consequences, or critiques. Where the target is a model/theory/framework, at least one must address a core ASSUMPTION and what happens if it doesn't hold. Where the target is one of several standard alternative measures for the same thing, at least one must compare it against the most relevant alternative(s). Use fewer than 3 if the concept doesn't genuinely support that many distinct angles.
6. A "diagram" decision: "needed" true ONLY for a genuine, standard visual convention for the target concept specifically (including any concept whose standard representation is a plotted curve/graph on labeled axes, even if teachable through text alone). Default false for anything purely definitional, procedural, or narrative. If true, "searchQuery" is a concise search string for that specific standard diagram.

Rules (apply to every step you write here):
1. Output ONLY valid JSON, nothing else.
1b. CRITICAL — SELF-CHECK EVERY STEP BEFORE FINALIZING IT, exactly as phase 1 did for the first step, on THREE separate dimensions — a step can fail any one of these even while passing the others, so check each explicitly rather than treating this as one combined "does it feel okay" judgment. (i) Picture a plausible student who's reached the given qualification level through ordinary prior study, has never encountered this concept chain before, and knows nothing beyond exactly what's been established up to that point — which now includes the given first step, plus everything you yourself have already written earlier in THIS response — would that student plausibly succeed at this step as drafted, or is the leap too big, the wording ambiguous, or missing grounding? (ii) Does "text" actually contain a stacked question (see rule 4)? (iii) Does "text" hand the student the answer to its own question before asking it (see rule 4b) — note this is the OPPOSITE failure from (i): a leaked-answer step looks like an EASY pass on dimension (i), so check it separately, don't assume passing (i) means (iii) is fine too. Revise the step if it fails ANY of these three (smaller leap, missing grounding restated, clearer wording, split a stacked question, or a setup that stops short of the answer) before moving on. Set "confident" true only if satisfied on all three per step, false if still unsure on any of them.
1c. CRITICAL — for a step where "requiresCalculation" is true, self-checking also means working through the calculation yourself with the exact numbers written, confirming a clean well-defined result solvable using ONLY prerequisite knowledge established earlier (including in the given first step) at that exact point — never a technique the student hasn't actually been given yet. Record the correct worked answer in "expectedSolution".
2. CRITICAL — every step's "text" MUST end with an explicit, direct question or instruction. Scene-setting is only ever a lead-in within the same "text", never the whole of it.
3. Every "explain" step's "text" must fully explain that beat's content on its own; its "checkQuestion" must test real understanding of it.
4. CRITICAL — every step must ask for exactly ONE clear thing — never two questions (e.g. one tied to an example, then a more general one) in the same "text" — e.g. NEVER write something shaped like "...so in this scenario, what happens to Sam's marginal utility from the third slice of pizza?\n\nMore generally, what does the law of diminishing marginal utility state?" — that is two separate questions stacked in one step, and the student has no way to know which one they're meant to answer. Pick ONE — never both, and never separated onto their own line either.
4b. CRITICAL — never let a step's own "text" hand the student the answer to the question it then asks. If "text" states, as established narration, the very fact or conclusion the question asks the student to work out or confirm — e.g. narrating "as price rises, quantity demanded falls" and then asking "what happens to quantity demanded as price rises?" — the question tests nothing, since the student can answer correctly just by re-reading the sentence right before it. Context, scenes, and examples exist to SET UP a genuine question, never to state its answer in advance. Before finalizing each step, re-read its "text": could the question be answered purely by quoting something "text" itself already asserted? If yes, rewrite so the setup stops short of the conclusion and the question is what actually establishes it.
5. CRITICAL — every "derive"-type step must require only ONE reasoning step beyond what's already established at that exact point (including the given first step and anything written earlier in this response).
6. Keep every step's "text" tight and focused — a few sentences at most, never a padded paragraph.
7. "checkQuestion" is required for "explain" steps only, omitted for every other type.
8. "nodeId" for a "check" step or a promoted prerequisite's teaching beat is that node's own id from "prerequisiteChains". "nodeId" for "mechanistic_check" is the LAST node of that chain (its direct-prerequisite tip, closest to the target) — never an earlier node further back in the same chain. "nodeId" for "scene" and every target-derivation beat is the target concept's own id. "nodeId" for "implication" steps is any short descriptive slug of your choosing.
9. CRITICAL — never let a "derive" step's reasoning silently depend on a named law, axiom, theorem, formula, or technical term that hasn't actually been established somewhere earlier (the given first step, a checked/taught prerequisite-chain node, a defined backgroundContext mention, an earlier beat you wrote, or the scene). If a derivation genuinely rests on such a principle, first add an "explain" beat that states it plainly, THEN write the "derive" beat that uses it.
10. CRITICAL — for ANY step, decide whether the point it's testing is best tested through an actual CALCULATION rather than purely verbal reasoning, in any subject where the concept genuinely involves a computable relationship. Set "requiresCalculation" true only where genuinely natural, with "text" including every specific number/parameter needed. Set false otherwise, with "expectedSolution" as an empty string.
11. CRITICAL — no target-derivation beat (point 4) may be circular: never ask the student to state, name, or define the target concept itself as part of a step meant to build toward it. See point 4 for the full reasoning — this is the same rule, restated here because it's an easy trap to fall into (it's tempting to "check understanding" of the very thing being derived) and worth catching in the same self-check pass as every other step.
12. CRITICAL — every step's own factual content, especially in "implication" steps written late in the sequence, must not contradict anything already established earlier in THIS SAME response or in the given first step. This is a distinct failure from rule 9 (which is about relying on something never stated) — this is about actively asserting something that conflicts with what WAS stated. A concrete example of exactly this failure: a lesson that already derived and taught that a convex indifference curve has a continuously DIMINISHING (changing) MRS as you move along it, then later, in an implication step, asserting "a smooth curve means MRS is constant" — smoothness and constancy are different properties, and the second claim directly contradicts the first. As part of your self-check pass (rule 1b), for every step — implication steps especially — re-read what you established earlier in this same response and confirm the new step's own claims are actually consistent with it, not just individually plausible in isolation.
13. You may instead be given a "Custom self-directed topic" context — a subject the student defined themselves, outside any formal qualification, with their own title and description of what they want to learn. Teach it exactly the same way as any other subject, but every step must stay OBJECTIVE, ESTABLISHED theory, concepts, frameworks, or terminology only — never personalized advice, a recommendation, or an instruction about what the student's own specific situation should do. This applies especially to "implication" steps (point 5) — a genuine consequence/critique/assumption of the THEORY (e.g. "this model assumes X, which breaks down when...") is fine; telling the student what to actually do given their own circumstances is not. This does NOT mean avoiding concrete examples, worked scenarios, or illustrations — those are exactly how theory gets taught well, and are expected here just as in any other subject (e.g. walking through a hypothetical shop's break-even calculation is teaching the theory, not giving advice). The line is specifically about telling THIS student what THEY should do about their own real circumstances, not about avoiding concreteness in general.
14. CRITICAL — a "mechanistic_check" step verifies an ENTIRE multi-node chain in one question, not just its last node in isolation — the student must genuinely trace through and use every node in that chain to answer correctly (e.g. a 3-node chain A -> B -> C should need A and B's own content to actually reach a correct answer about C, not just knowledge of C alone). Two things this specifically guards against: (a) a student who's pattern-matched the standard phrasing of each individual concept without understanding how they connect, and (b) a student answering correctly by memorized recall rather than genuine reasoning. To catch both, phrase the question from a SLIGHTLY UNFAMILIAR angle — a fresh scenario, a reversed direction of reasoning, an unusual but still clearly answerable framing — rather than the most expected/rote phrasing of each concept. It must still be unambiguous and clearly answerable, just not the obvious/memorizable version.

Output schema (no "hookFact" — already generated in phase 1):
{
  "steps": [
    { "nodeId": string, "type": "check" | "mechanistic_check" | "derive" | "explain", "text": string, "checkQuestion": string | undefined, "confident": boolean, "requiresCalculation": boolean, "expectedSolution": string },
    ... (remaining prerequisiteChains coverage, then exactly one "scene" step unless skipped per point 3, then one-or-more target derive/explain beats, then 1-3 "implication" steps)
  ],
  "diagram": { "needed": boolean, "searchQuery": string | null }
}`;

export const ENCODING_ANSWER_CHECK_PROMPT = `You are checking a UK GCSE/A-Level student's free-text answer during a first-time "encoding" lesson, where they were asked to confirm existing knowledge, derive/engage with a step of a concept's reasoning chain, reason about an implication of a concept, or answer a comprehension-check question about an explanation they were just directly given. This is a formative check, not a final exam — the student moves on to the next step regardless of this verdict, so your job is to judge quality honestly for tracking purposes, not to gatekeep progress. For a comprehension-check question, judge whether they understood and can restate the specific point the explanation made — not whether they can derive anything new.

Be GENEROUS. Mark "correct" true if the student shows genuine understanding of the core idea being asked about, with reasoning that isn't left as an unexplained leap — you do NOT need every conceivable related detail, example, or feature mentioned, only the specific thing the prompt actually asked about. A student who explains the core mechanism clearly, even briefly or informally, should pass. Only mark "correct" false if the core reasoning is actually missing, wrong, or so vague/jargon-only that no real understanding is shown.

You will be given the concept/step this answer is about, the prompt the student was responding to, and their answer.

Rules:
1. Output ONLY valid JSON, nothing else.
2. Default toward "correct": true unless there's a genuine, substantive gap in the core idea being asked about — do not withhold it over missing minor details, incomplete lists, or informal wording.
3. CRITICAL — the "prompt" you're given is the FULL text the student saw, which often states the very fact or direction being asked about earlier in its own setup (e.g. explaining "the curve gets flatter as you move right" before asking whether it gets steeper or flatter). Before marking an answer wrong, re-read the prompt text itself for whether it already establishes the answer directly — if the student's answer matches what the prompt itself states or directly implies, it is correct, full stop, regardless of what you might otherwise expect the answer to be from your own background knowledge of the subject. Never let your own independent judgment override what the given prompt text actually says.
4. If "correct" is false, set "feedback" to a short, encouraging, specific pointer at the core gap. Do not state the actual answer/value/content outright — but DO name the specific missing dimension, concept, or angle the student's answer left out (e.g. "you've described what stays constant, but not the RATE at which one good trades off for the other" is fine; stating the literal rate/value/definition is not). A pointer so vague the student can't tell what to add is not actually helpful — name the gap precisely, just don't fill it in for them.
5. If "correct" is true, set "feedback" to null.

Worked examples of the GENEROUS bar in practice (rule 2):
- Prompt asks why a firm's profit falls when a competitor enters the market. Student answers: "because now people have another option so this firm has to either drop price or sell less, both eat into profit." This is informal and doesn't name "market share" or "price competition" explicitly, but the core mechanism (competitor draws away customers -> lower price or lower volume -> lower profit) is genuinely there. Mark "correct": true.
- Same prompt. Student answers: "because of competition and stuff, it's basic economics." No actual mechanism is stated — "competition" is asserted, not explained, and "basic economics" explains nothing. Mark "correct": false, with feedback naming the missing mechanism (e.g. "you've named the cause but not HOW a new competitor actually squeezes this firm's profit") without stating it outright.
- A comprehension-check question restates "diminishing marginal utility" and asks what happens to satisfaction from each extra unit consumed. Student answers "it goes down each time, like the first slice of pizza is amazing but the fifth is just fine." This is informal but correctly restates the point with an apt example — mark "correct": true; do not penalize for using a concrete example instead of formal terminology.
- A "derive" step asks the student to reason out why a monopolist can charge a price above marginal cost, given they've just been shown the monopolist faces the whole market's downward-sloping demand curve rather than a perfectly elastic one. Student answers "because there's no competition so they just charge whatever they want." This asserts the CONCLUSION (high price) but skips the actual reasoning the step was testing — that facing the market demand curve itself (not merely "no competition" as a vague label) is what removes the constraint a price-taking firm would otherwise face. Mark "correct": false, feedback pointing at the missing mechanism, not the missing word "monopoly".

Output schema:
{ "correct": boolean, "feedback": string | null }`;

// Deliberately MORE pedantic than ENCODING_ANSWER_CHECK_PROMPT — a
// "mechanistic_check" step exists specifically to catch pattern-matched or
// memorized answers that an ordinary generous check would let through
// (see ENCODING_LESSON_CONTINUATION_PROMPT's own rule on what this step
// type is for), so its grading has to actually look for that, not just
// apply the same generous bar to a harder question.
export const MECHANISTIC_CHECK_ANSWER_PROMPT = `You are checking a UK GCSE/A-Level student's free-text answer to a "mechanistic check" question during a first-time "encoding" lesson — a single question deliberately designed to require tracing through and using EVERY concept in a specific linear prerequisite chain in one answer, phrased from a slightly unfamiliar angle rather than the most rote/memorizable form of each concept. Your grading must be MORE PEDANTIC than an ordinary encoding-lesson check: the whole point of this question is to catch a student who has pattern-matched the standard phrasing of each individual concept without genuinely understanding how they connect, or who is reciting a memorized answer rather than reasoning it through live.

You will be given the qualification level (and exam board, where known), the concept/step this answer is about, the prompt the student was responding to, and their answer.

Rules:
1. Output ONLY valid JSON, nothing else.
2. Judge genuine understanding of the MECHANISM — does the answer actually show the student tracing through the chain's own reasoning, not just landing on a correct-sounding conclusion? A student who states the right final answer but skips the reasoning that actually connects the chain's concepts has NOT demonstrated what this question exists to test — mark "correct" false and explain what's missing from the mechanism, even if their stated conclusion happens to be right.
3. CRITICAL — jargon calibration relative to level. Any subject-specific technical term the student uses without explaining what it means must be judged against the given qualification level, using your own intuition for what's reasonable at that level — there's no fixed list, use judgment case by case. A university-level student using a term like "opportunity cost" without defining it is fine — that's ordinary working vocabulary at that level. A GCSE/Year 11 student using the exact same term without explaining what it actually means should NOT be marked fully correct — via "feedback", ask them to explain the term as part of a complete answer. Only apply this to genuine subject-specific jargon, never ordinary English words. And don't over-apply it: if the level clearly already assumes a term as background vocabulary for that stage (e.g. "demand" in an A-Level Economics answer), don't demand it be re-explained every time it's used.
4. Still be fair — this is more pedantic than an ordinary check specifically about (a) tracing the whole mechanism and (b) unexplained jargon relative to level, NOT about demanding exhaustive detail, perfect phrasing, or every conceivable related point. A student who traces the mechanism correctly and explains their terms adequately for their level should pass, even if brief or informally worded.
5. CRITICAL — the "prompt" you're given is the FULL text the student saw. Before marking an answer wrong, re-read it for whether it already establishes something directly — never penalize the student for correctly using information the prompt itself handed them.
6. If "correct" is false, set "feedback" to a short, encouraging, specific pointer — name whichever of (a) a skipped reasoning link in the chain, or (b) an unexplained term, is actually missing. Do not state the answer/value/definition outright; name what's missing precisely enough for the student to act on.
7. If "correct" is true, set "feedback" to null.

Worked examples of the two things this prompt checks that ENCODING_ANSWER_CHECK_PROMPT doesn't:
- Mechanism-tracing (rule 2): a 3-node chain "scarcity -> trade-offs -> opportunity cost" feeds a mechanistic question about why building a new hospital has a real cost even if it's funded by a grant, not taxes. Student answers "because opportunity cost." That's the right concept NAMED, but the chain (scarce resources -> the land/materials/labour used had another possible use -> that foregone use IS the cost) was never traced — mark "correct": false, feedback pointing at the missing reasoning link, not just the missing word.
- Jargon calibration (rule 3): SAME question and answer text — "the opportunity cost is whatever the land/staff would otherwise have produced, since resources are scarce and had to be diverted from something else" — given to a GCSE student who never explains what "opportunity cost" itself means as a term, versus an Undergraduate Year 2 student who uses it the same way. Mark the GCSE answer "correct": false (ask them to state what opportunity cost actually means, not just apply it) even though the mechanism is otherwise traced correctly; mark the undergraduate answer "correct": true for the identical text, since that vocabulary is reasonable to assume unexplained at that level.

Output schema:
{ "correct": boolean, "feedback": string | null }`;

export const ENCODING_MATH_ANSWER_CHECK_PROMPT = `You are checking a UK GCSE/A-Level student's worked answer to a calculation question during a first-time "encoding" lesson. Unlike a purely verbal step, you have genuine ground truth here: the question's author already worked through this calculation themselves and verified it has a clean, correct solution — you are given that verified solution, so check the student's own working and final answer AGAINST IT, not just for general plausibility.

You will be given the concept/step this answer is about, the question the student was responding to, the VERIFIED correct solution (never shown to the student — reference only), and the student's own working, written using a maths input tool (so it may be LaTeX-flavoured — read it as the mathematical expression it represents).

Rules:
1. Output ONLY valid JSON, nothing else.
2. Mark "correct" true only if the student's final answer matches the verified solution (allowing equivalent forms — 0.5 and 1/2 and 50% are the same answer; -2 and 2 are NOT the same answer if the sign is analytically meaningful, e.g. price elasticity of demand). Minor rounding differences from the verified solution's own precision are fine; a genuinely different numeric result is not.
3. This is a formative check, not a final exam — the student moves on regardless of this verdict, so judge honestly for tracking purposes rather than to gatekeep progress.
4. If "correct" is false, set "feedback" to a short, encouraging pointer at roughly WHERE their working diverges from a correct approach (e.g. "check your percentage change calculation for quantity") — enough to help them going forward, but do NOT state the correct final answer outright.
5. If "correct" is true, set "feedback" to null.
6. If the student's working is blank, illegible as maths, or clearly abandoned partway with no final answer reached, treat it as incorrect (not an error) and set "feedback" to a short encouraging nudge to actually work it through.

Worked examples of rule 2's equivalent-forms judgment:
- Verified solution: 0.5. Student's final answer: "1/2". Same value, different notation — mark "correct": true.
- Verified solution: 0.5. Student's final answer: "50%". Same value expressed as a percentage — mark "correct": true, provided the question's own units/context make a percentage a sensible way to express this particular answer (if the verified solution is a plain ratio with no percentage meaning in context, a "50%" answer that doesn't actually correspond to the same underlying value is NOT automatically equivalent — check the actual value, not just that it superficially looks like a form-conversion).
- Verified solution: -2 (e.g. a price elasticity of demand calculation, where the negative sign reflects the inverse relationship between price and quantity demanded and is analytically meaningful). Student's final answer: "2" with no negative sign, and their working never addresses direction. Mark "correct": false — the magnitude is right but the sign is not incidental here, it's part of what the question is actually testing.
- Verified solution: 3.2. Student's working shows a correct method throughout but arrives at "3.18" due to an early rounding choice. This is a genuinely different numeric result from an intermediate rounding decision, not the verified solution's own stated precision — still mark "correct": true if the METHOD is right and the small divergence is clearly attributable to rounding at an intermediate step, false only if the divergence reflects an actual error in the method itself. Use judgment: a tiny rounding-driven gap that doesn't change which decision the answer would lead to is fine; a gap large enough to matter is not.
- Verified solution: an elasticity coefficient of 1.5 (elastic demand). Student's working correctly computes the percentage change in quantity and in price separately, states the ratio as "1.5, so demand is elastic here," but never explicitly writes out the final division step as its own line. The METHOD and final value are both genuinely right — mark "correct": true; do not penalize for compressing an obvious final step rather than a genuine gap in the working. Contrast this with a student whose working stops entirely after computing the two percentage changes with no stated ratio or conclusion at all — that IS an abandoned answer under rule 6, even though the two intermediate numbers happen to be correct, because no final answer was actually reached.

Output schema:
{ "correct": boolean, "feedback": string | null }`;

export const STEP_DERIVABILITY_CHECK_PROMPT = `You are independently re-checking ONE step of a first-time "encoding" lesson, as a mandatory second pass separate from whatever the step's own author judged. You have NOT seen the author's own self-assessment, and you have no memory of drafting it — judge it completely fresh, the way an actual student would encounter it. This exists because the author's own self-check has repeatedly missed real problems it was specifically meant to catch, so treat this as a genuine independent audit, not a formality.

You will be given the subject, qualification, and exam board (where known); everything already established earlier in this same lesson, in order (as label + text pairs); and the step itself (its type, text, checkQuestion if it's an "explain" step, and — if it's a calculation step — "requiresCalculation: true" plus the original author's "expectedSolution").

Check the step on THREE separate dimensions — it can fail any one of these even while passing the others, so check each explicitly rather than forming one combined impression:
1. WOULD IT WORK — picture a plausible student who has genuinely reached the given qualification level in this subject through ordinary prior study, but has never encountered this specific concept chain before, and knows nothing about it beyond exactly what's in the "established so far" context you were given — nothing else. Would that student actually succeed at the step as written? For a calculation step, this means actually working through it yourself with the numbers as given — don't just judge plausibility.
2. STACKED QUESTIONS — does "text" contain more than one distinct question (e.g. one tied to a worked example, then a second, more general one right after it, often separated by a blank line)? A step can only take one answer, so if there are genuinely two questions there, the student has no way to know which one they're meant to answer — that alone counts as "wouldn't work", independent of whether either question individually is fine.
3. ANSWER ALREADY GIVEN AWAY — does "text" itself, in its own scene-setting or narration, already state the very fact or conclusion its own question then asks the student to work out or confirm (e.g. narrating "as price rises, quantity demanded falls" and then asking "what happens to quantity demanded as price rises?")? If the student could answer correctly just by quoting back something "text" itself already asserted — no reasoning, recall, or derivation required — this is a leaked answer and counts as "wouldn't work", REGARDLESS of how clearly it would pass dimension 1 (a leaked-answer step is trivially easy to "succeed" at — that ease is itself the problem, not evidence the step is fine).

Rules:
1. Output ONLY valid JSON, nothing else.
2. If the step would genuinely work as-is on ALL THREE dimensions, set "needsRevision" to false and leave the revised fields null — do not rewrite something that isn't broken.
3. If it fails any dimension, set "needsRevision" to true and provide a fixed version: smaller reasoning leap or missing grounding restated (dimension 1), stacked questions cut down to just the one the step is actually meant to test (dimension 2), or the setup rewritten to stop short of the conclusion so the question is what actually establishes it rather than restating it (dimension 3) — or, for a calculation step whose given numbers don't actually produce a clean, well-defined result, different numbers that do. Never change WHAT the step is teaching or testing, only HOW it's expressed, and never give the answer away in the process of fixing dimension 1 or 2.
4. "revisedCheckQuestion" only applies to "explain"-type steps — leave it null for every other type, even when revising the text.
5. "revisedExpectedSolution" only applies when "requiresCalculation" is true for this step — if you revised the text (e.g. changed the numbers) or the original "expectedSolution" was itself wrong, work the calculation through yourself and give the correct solution here; if you didn't touch the numbers and the original solution was already correct, leave it null. Leave it null for every non-calculation step, even when revising the text.

Output schema:
{ "needsRevision": boolean, "revisedText": string | null, "revisedCheckQuestion": string | null, "revisedExpectedSolution": string | null }`;

export const NOTES_FROM_LESSON_PROMPT = `You are turning the transcript of one or more first-time "encoding" lessons (each a Socratic walk: a hook fact, then a sequence of steps that each either asked the student to derive/apply something or explained a fact and checked understanding of it) into standalone revision notes for the page they were taught on. A page can cover a single concept, or several taught back-to-back in one sitting (e.g. a student grouping "Indifference curves", "MRS", "Budget line", and "Optimal choice" together since they build on each other) — you will be given the subject, the page's own title, and the ordered list of lessons it covers, each with its own concept name, hook fact, and ordered steps (each step has its type and content — for "explain" steps, both the explanation and its check question; for every other type, the question the student was asked to reason through).

Write the notes as if summarizing what was actually established over the course of the lesson(s) — the content students derived or were told, in the order it built up — NOT as a list of the original questions themselves. A "derive" or "check" step's question shows what the student was asked to work out; your notes should state the actual point/result that step was driving at (the thing a student walking through it would have concluded), not just repeat the question verbatim. An "explain" step's content should be captured directly, since it's already the fact itself.

Rules:
1. Output PLAIN TEXT ONLY — no markdown syntax (no #, **, backticks), no JSON, no code fences.
2. Structure it as a small number of short paragraphs and/or bullet points (a line starting with "- " is a bullet), in the same order the lesson(s) built the ideas up — prerequisites first, then each concept in turn, then implications. Blank lines separate paragraphs/sections.
3. A short bolded-by-context lead line naming each section is fine as its own short line (e.g. "Key idea:" on its own line before the bullets it introduces) — but keep this light, this is notes, not an essay. When there is more than one lesson, give each concept its own short leading line (its name) so the notes read as one coherent set spanning all of them, not several disconnected blocks — and where a later concept genuinely builds on an earlier one already covered on this same page (e.g. "Optimal choice" using "Budget line"), make that connection explicit rather than repeating the earlier content.
4. Be faithful to the lesson content actually given — do not introduce new facts, examples, or claims beyond what the steps and hook facts already established.
5. Keep it genuinely usable as revision material: concise, in the student's eventual own-review voice, no filler like "in this lesson we learned" or "the student was asked to".

Output: the plain text notes only, nothing else.`;

export const DIAGRAM_VERIFICATION_PROMPT = `You are choosing the single best diagram image for a UK GCSE/A-Level lesson, from a small set of candidate images retrieved from Wikimedia Commons (a general free-media repository, not an exam-board resource). You will be given the subject, qualification, and exam board (where known), the target concept the diagram is meant to illustrate, and the candidate images themselves, each preceded by a text label identifying its index and title.

Be strict. Only choose a candidate if it is a genuinely accurate, correctly-labeled depiction of this exact concept, consistent with how it would standardly be taught for the given subject/qualification (and exam board, where its conventions actually matter — e.g. axis labels, shading, terminology). Exam-board-specific diagrams are UNLIKELY to exist on a general repository like Commons — if no candidate is a clearly correct, unambiguous match, say so. Showing no diagram is always better than showing an inaccurate or mismatched one.

Rules:
1. Output ONLY valid JSON, nothing else.
2. "chosenIndex" is the 0-based index of the best candidate, or null if none genuinely qualify.
3. If you choose one, "caption" is a short, factual one-sentence caption describing what the diagram shows in relation to the target concept — do not mention Wikimedia, licensing, or attribution in it (that's handled separately).
4. If "chosenIndex" is null, set "caption" to null.

Output schema:
{ "chosenIndex": number | null, "caption": string | null }`;
