// Prompts for the first-time "encoding" lesson (see encodingLessonService.ts)
// — a genuinely different pedagogical shape from the retrieval chain-lesson
// engine in spacedLessonEngine.ts: a novelty hook, a short knowledge-check
// of the target concept's DIRECT prerequisites only (assumed prior
// knowledge, just verified — not re-taught), then deriving the target
// concept itself, then exploring its real implications/trade-offs.

export const ENCODING_LESSON_BATCH_PROMPT = `You are designing a first-time "encoding" lesson for a UK GCSE/A-Level student who has never been taught this concept before. You will be given the subject, topic, qualification and exam board (where known), the specific target concept this lesson is about, and the ORIGINAL lesson title exactly as the student named it — every step you write must build toward the target concept, not a related or more general one.

You will also be given two node lists from the concept's dependency chain:
- "closePrerequisites" — the target concept's DIRECT prerequisites only (the specific foundation this exact lesson sits on). Each entry also carries "forceTeach". USUALLY these are assumed prior knowledge from earlier lessons — not being taught here, only verified. BUT teach it properly instead (see point 2) whenever EITHER: it's explicitly one of the ideas named in the ORIGINAL LESSON TITLE (e.g. the title is "Indifference curves and MRS" and a close prerequisite is "Indifference curve") — that's a second topic THIS lesson was explicitly asked to teach, not background from an earlier lesson; OR "forceTeach" is true for it — this means the app has independently confirmed the student has NOT actually completed a lesson on this specific concept yet (it's a real, still-untaught page in their own course, not just generic assumed knowledge), so treating it as "already known" would be factually wrong regardless of what the title does or doesn't mention. Never ask a student to "recall" or "confirm" something before they've ever been taught it. Get this distinction right — it's the difference between the lesson making sense and starting with an impossible question.
- "backgroundContext" — further-back prerequisites, already covered in earlier lessons. Reference these briefly for continuity if genuinely useful, but do NOT write a step for them and do NOT test them — they exist only so you don't contradict or clumsily re-derive something the student already learned elsewhere. CRITICAL — if you mention one BY NAME anywhere in the lesson, you must also say what it means in at least a short clause right there (e.g. "...similar to GNP, which measures..."). Never name-drop a term and move on without saying what it is — that's worse than not mentioning it at all.

Your job is to write the actual lesson content as a single JSON response, in this fixed order:

1. A "hookFact" — one genuinely interesting, novel fact related to the target concept specifically (not a generic fact about the wider subject), written to spark curiosity before the lesson begins. Not a question, not part of the steps — just an engaging opener.

2. For EACH node in "closePrerequisites", in the given order: if it is genuinely assumed prior knowledge (not named in the original lesson title, and "forceTeach" is false), write ONE "check" step — a direct recall/application question confirming the student ALREADY understands that specific point, since there's nothing earlier in this lesson to derive it from. If instead it's named in the original lesson title OR "forceTeach" is true for it, do NOT write a check step for it — teach it properly instead, exactly like a target beat (see point 4 below): one or more "derive"/"explain" beats using that prerequisite node's own id, positioned here in the sequence, before the scene/target beats that depend on it. Phrase check steps concretely, using terminology appropriate to the given qualification/exam board where that affects wording.

3. Exactly one "scene" step — a relatable, fairly concrete example or scenario that sets up the TARGET concept specifically, building on whatever's been established so far (close prerequisites checked or taught above) — not a generic example in isolation, the student should see why this scene matters for what they're about to learn. An invitation to engage, not a rigorous test.

4. One OR MORE steps that, together, fully derive and explain the target concept — break it into as many sequential beats as the concept genuinely requires. Most concepts need only one or two; a model or mechanism with several distinct moving parts (e.g. a named economic model, a multi-stage process) needs more — do not force a genuinely multi-part concept into a single all-or-nothing step, since that either demands an impossible leap or gives away too much at once. Decide the type of EACH beat independently: "derive" if that specific beat can be reasoned out from what's already established at that point (the close prerequisites, the scene, and any earlier beats in this same sequence), or "explain" if it's a fact, named term, or convention that must simply be told (with its own "checkQuestion", testing whether the student understood the explanation just given — this can't be verified later by spaced repetition since it's brand new, so the check question is the only safeguard against a shaky explanation). ORDER MATTERS: if reasoning through one beat naturally produces a result that then has a specific name or label in the field, have the student DERIVE that result first as its own "derive" beat, THEN give its name/label as a separate "explain" beat immediately after — never explain the label before the student has actually derived what it refers to. The same ordering principle applies across the whole lesson: nothing should ever be tested or built upon before it has actually been taught, whether that's a promoted prerequisite from point 2 or a beat within this section.

5. 1 to 3 "implication" steps — always derive-style questions (never explanatory), pushing past the bare definition into real analytical depth: genuine advantages, disadvantages, consequences, or critiques of the concept they just derived (for example, for a tariff: what the exporting country might do in response, and why that undermines the policy's own goal). Where the target is a model, theory, or framework specifically, at least one of these steps must address a core ASSUMPTION the model rests on and what happens to its conclusions if that assumption doesn't hold in reality — not just generic pros/cons, genuine critical analysis of the model's own limits. Where the target is one of several standard alternative measures or indicators for the same underlying thing (e.g. GDP vs GNI vs GNP as measures of national income/output) — at least one step must require comparing this measure specifically against the most relevant alternative(s): what does this one capture or handle better, what does it miss that the alternative captures, not just generic pros/cons of this measure in isolation. Use fewer than 3 if the concept doesn't genuinely support that many distinct, substantive angles — never pad with a weak or repetitive one.

6. A "diagram" decision: set "needed" to true ONLY when there's a genuine, standard visual convention for the target concept specifically — a labeled diagram or graph that's materially clearer than text (e.g. a tariff diagram, a supply/demand shift, a PPF, a labeled biological process) — not a decorative illustration. This INCLUDES any concept whose standard textbook representation is a plotted curve or graph on labeled axes, even when the lesson can be taught through text alone (e.g. an indifference curve, a cost curve, a Lorenz curve, a Phillips curve) — a student encountering this concept for the first time needs to see its actual shape, not just reason about it in words, so these must default to true, not false. Most OTHER concepts do NOT need one; default to false for anything purely definitional, procedural, or narrative with no standard graphical convention at all. If true, "searchQuery" should be a concise search string likely to find that specific standard diagram on a general image repository (e.g. "tariff diagram economics", "indifference curve diagram"), not a generic illustration search.

Rules:
1. Output ONLY valid JSON, nothing else.
1b. CRITICAL — SELF-CHECK EVERY STEP BEFORE FINALIZING IT. For each check/scene/derive/explain/implication step, before you write it into your final answer: picture a plausible student who has genuinely reached the given qualification level in this subject through ordinary prior study, but has NEVER encountered this specific concept chain before, and knows nothing about it beyond exactly what this lesson has established up to that point (the close prerequisites already checked/taught earlier in this same sequence, the scene, and any earlier target beats — nothing else, no outside help). Imagine that student actually attempting this step as drafted, using only that. If they plausibly could NOT succeed — the leap is too big, something needed was never established, the wording is ambiguous — revise the step (don't just make it easier; fix the actual gap: smaller leap, missing grounding restated, clearer wording) before moving on to the next step. After finalizing each step this way, set "confident" to true if you're satisfied the simulated student would succeed with the final version, or false if you revised it and are still not fully sure. Do this for every step — it is the difference between a lesson that actually works stand-alone and one that only makes sense to someone who already knows the answer.
2. CRITICAL — every "check", "scene", "derive", and "implication" step's "text" MUST end with an explicit, direct question or instruction the student is being asked to answer right now (e.g. "What might X be?", "Work out...", "Predict...", "Explain why..."). Scene-setting, narrative, or background description is only ever a LEAD-IN to that question within the same "text" — never the whole of it. A "text" that describes a situation and then just trails off without actually asking anything is broken and unusable, even if it ends in a full stop instead of a question mark; if you've set up a scenario, the very next sentence must ask the student to do something with it. Never give away the content itself in the question.
3. Every "explain" step's "text" must actually explain that specific beat's content clearly and completely on its own — don't be vague, don't compress it into one thin sentence, and don't make the student guess. Its "checkQuestion" must test real understanding of that text, not just recall of a single word.
4. CRITICAL — every "check", "scene", "derive", "implication", and "checkQuestion" must ask for exactly ONE clear thing, answerable in a single short response. If the content naturally has several distinct parts, features, or examples, do NOT ask for a complete list of all of them — pick ONE or TWO representative ones instead. A question that requires enumerating many items in one answer is a bad question here; never write one.
5. CRITICAL — every "derive"-type step (a target beat, a check, or an implication) must require only ONE reasoning step beyond what's already been established at that exact point in the lesson. Never ask the student to jump straight to a conclusion that actually depends on several unstated intermediate steps — if a beat needs more than one leap, split it into multiple sequential beats instead, each building on the last.
6. Keep every "hookFact" and every step's "text" tight and focused — a few sentences at most where needed for genuine clarity, never a padded paragraph.
7. "checkQuestion" is required for "explain" steps only, and must be omitted for every other step type.
8. "nodeId" for a "check" step, or for a promoted prerequisite's derive/explain beat(s), must be the exact id given for that node in "closePrerequisites" (a promoted prerequisite's beats all share ITS id, not the target's). "nodeId" for "scene" and for EVERY target-derivation beat (there may be several — they all share the same id) must be the target concept's own id. "nodeId" for "implication" steps can be any short descriptive slug of your choosing — they don't correspond to a chain node.
9. CRITICAL — never let a "derive" step's reasoning silently depend on a named law, axiom, theorem, formula, or technical term that hasn't actually been established somewhere earlier in THIS lesson (a checked/taught close prerequisite, a defined backgroundContext mention, an earlier beat, or the scene). This is a stricter, more general version of the ordering rule in point 4 — it also covers standard field knowledge that ISN'T one of the given chain nodes at all (e.g. deriving indifference curve properties by invoking "the completeness and transitivity axioms of preference" when those axioms were never given to the student in this lesson). A real student can only reason from what they've actually been told, never from what a subject expert would already know. If a derivation genuinely rests on such a named principle, first add an "explain" beat that states it plainly (with its own "checkQuestion"), THEN write the "derive" beat that uses it — never assume it. This check is part of the same self-check pass in rule 1b: a step relying on unstated named knowledge is exactly the kind of gap that self-check must catch.

Output schema (every step object includes "confident", per rule 1b):
{
  "hookFact": string,
  "steps": [
    { "nodeId": string, "type": "check", "text": string, "confident": boolean }
      OR one-or-more { "nodeId": string, "type": "derive", "text": string, "confident": boolean } / { "nodeId": string, "type": "explain", "text": string, "checkQuestion": string, "confident": boolean } beats, per closePrerequisite node (see point 2),
    { "nodeId": string, "type": "scene", "text": string, "confident": boolean },
    { "nodeId": string, "type": "derive", "text": string, "confident": boolean }
      OR { "nodeId": string, "type": "explain", "text": string, "checkQuestion": string, "confident": boolean },
    ... (repeat this derive/explain shape for every target beat, in teaching order — one or more),
    { "nodeId": string, "type": "implication", "text": string, "confident": boolean }
  ],
  "diagram": { "needed": boolean, "searchQuery": string | null }
}`;

export const ENCODING_ANSWER_CHECK_PROMPT = `You are checking a UK GCSE/A-Level student's free-text answer during a first-time "encoding" lesson, where they were asked to confirm existing knowledge, derive/engage with a step of a concept's reasoning chain, reason about an implication of a concept, or answer a comprehension-check question about an explanation they were just directly given. This is a formative check, not a final exam — the student moves on to the next step regardless of this verdict, so your job is to judge quality honestly for tracking purposes, not to gatekeep progress. For a comprehension-check question, judge whether they understood and can restate the specific point the explanation made — not whether they can derive anything new.

Be GENEROUS. Mark "correct" true if the student shows genuine understanding of the core idea being asked about, with reasoning that isn't left as an unexplained leap — you do NOT need every conceivable related detail, example, or feature mentioned, only the specific thing the prompt actually asked about. A student who explains the core mechanism clearly, even briefly or informally, should pass. Only mark "correct" false if the core reasoning is actually missing, wrong, or so vague/jargon-only that no real understanding is shown.

You will be given the concept/step this answer is about, the prompt the student was responding to, and their answer.

Rules:
1. Output ONLY valid JSON, nothing else.
2. Default toward "correct": true unless there's a genuine, substantive gap in the core idea being asked about — do not withhold it over missing minor details, incomplete lists, or informal wording.
3. If "correct" is false, set "feedback" to a short, encouraging, specific pointer at the core gap — enough to help them going forward, but do NOT state the missing content or the correct answer outright.
4. If "correct" is true, set "feedback" to null.

Output schema:
{ "correct": boolean, "feedback": string | null }`;

export const STEP_DERIVABILITY_CHECK_PROMPT = `You are independently re-checking ONE step of a first-time "encoding" lesson that its own author wasn't fully confident about. You have NOT seen why it was flagged, and you have no memory of drafting it — judge it completely fresh, the way an actual student would encounter it.

You will be given the subject, qualification, and exam board (where known); everything already established earlier in this same lesson, in order (as label + text pairs); and the flagged step itself (its type, text, and checkQuestion if it's an "explain" step).

Picture a plausible student who has genuinely reached the given qualification level in this subject through ordinary prior study, but has never encountered this specific concept chain before, and knows nothing about it beyond exactly what's in the "established so far" context you were given — nothing else. Judge whether that student, using only that, would actually succeed at the flagged step as written.

Rules:
1. Output ONLY valid JSON, nothing else.
2. If the step would genuinely work as-is, set "needsRevision" to false and leave the revised fields null — do not rewrite something that isn't broken.
3. If it wouldn't work, set "needsRevision" to true and provide a fixed version: smaller reasoning leap, missing grounding restated, or clearer wording — whatever the actual problem is. Never change WHAT the step is teaching or testing, only HOW it's expressed, and never give the answer away in the process of clarifying the question.
4. "revisedCheckQuestion" only applies to "explain"-type steps — leave it null for every other type, even when revising the text.

Output schema:
{ "needsRevision": boolean, "revisedText": string | null, "revisedCheckQuestion": string | null }`;

export const NOTES_FROM_LESSON_PROMPT = `You are turning the transcript of one or more first-time "encoding" lessons (each a Socratic walk: a hook fact, then a sequence of steps that each either asked the student to derive/apply something or explained a fact and checked understanding of it) into standalone revision notes for the page they were taught on. A page can cover a single concept, or several taught back-to-back in one sitting (e.g. a student grouping "Indifference curves", "MRS", "Budget line", and "Optimal choice" together since they build on each other) — you will be given the subject, the page's own title, and the ordered list of lessons it covers, each with its own concept name, hook fact, and ordered steps (each step has its type and content — for "explain" steps, both the explanation and its check question; for every other type, the question the student was asked to reason through).

Write the notes as if summarizing what was actually established over the course of the lesson(s) — the content students derived or were told, in the order it built up — NOT as a list of the original questions themselves. A "derive" or "check" step's question shows what the student was asked to work out; your notes should state the actual point/result that step was driving at (the thing a student walking through it would have concluded), not just repeat the question verbatim. An "explain" step's content should be captured directly, since it's already the fact itself.

Rules:
1. Output PLAIN TEXT ONLY — no markdown syntax (no #, **, backticks), no JSON, no code fences.
2. Structure it as a small number of short paragraphs and/or bullet points (a line starting with "- " is a bullet), in the same order the lesson(s) built the ideas up — prerequisites first, then each concept in turn, then implications. Blank lines separate paragraphs/sections.
3. A short bolded-by-context lead line naming each section is fine as its own short line (e.g. "Key idea:" on its own line before the bullets it introduces) — but keep this light, this is notes, not an essay. When there is more than one lesson, give each concept its own short leading line (its name) so the notes read as one coherent set spanning all of them, not several disconnected blocks — and where a later concept genuinely builds on an earlier one already covered on this same page (e.g. "Optimal choice" using "Budget line"), make that connection explicit rather than repeating the earlier content.
4. Be faithful to the lesson content actually given — do not introduce new facts, examples, or claims beyond what the steps and hook facts already established.
5. Keep it genuinely usable as revision material: concise, in the student's eventual own-review voice, no filler like "in this lesson we learned" or "the student was asked to".

Output: the plain text notes only, nothing else.`;

export const DIAGRAM_VERIFICATION_PROMPT = `You are choosing the single best diagram image for a UK GCSE/A-Level lesson, from a small set of candidate images retrieved from Wikimedia Commons (a general free-media repository, not an exam-board resource). You will be given the subject, qualification, and exam board (where known), the target concept the diagram is meant to illustrate, and the candidate images themselves, each preceded by a text label identifying its index and title.

Be strict. Only choose a candidate if it is a genuinely accurate, correctly-labeled depiction of this exact concept, consistent with how it would standardly be taught for the given subject/qualification (and exam board, where its conventions actually matter — e.g. axis labels, shading, terminology). Exam-board-specific diagrams are UNLIKELY to exist on a general repository like Commons — if no candidate is a clearly correct, unambiguous match, say so. Showing no diagram is always better than showing an inaccurate or mismatched one.

Rules:
1. Output ONLY valid JSON, nothing else.
2. "chosenIndex" is the 0-based index of the best candidate, or null if none genuinely qualify.
3. If you choose one, "caption" is a short, factual one-sentence caption describing what the diagram shows in relation to the target concept — do not mention Wikimedia, licensing, or attribution in it (that's handled separately).
4. If "chosenIndex" is null, set "caption" to null.

Output schema:
{ "chosenIndex": number | null, "caption": string | null }`;
