// One-time content generation for a knowledge-map node/edge (see
// knowledgeMapPrompts.ts for the map itself). Generated once per node/edge,
// stored, served identically to every student - never regenerated per
// click. Both prompts are written for LEAN output on purpose: the actual
// $ cost of this pipeline is almost entirely output tokens (Sonnet output
// is billed several times higher than input), so trimming padding here is
// a real cost lever, not just a style preference - it does not trade away
// teaching quality, since the atomicity rules already guarantee each node
// is a single, small, well-scoped idea that doesn't need a long
// explanation to cover properly.

export const KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT = `You are writing the ENCODING lesson for one atomic node in a subject's knowledge-map graph - the first time a student meets this specific concept. You will be given the subject, qualification, exam board, subtopic, this node's own label, the labels of every node that lists this one as a direct prerequisite ("leads to"), and the labels of this node's own direct prerequisites (concepts the student has ALREADY been taught, immediately before this one).

Your job: teach this concept, and ONLY this concept, to real exam-board depth.

## Rules

1. **Explain the concept itself, completely, in as few words as that genuinely takes.** Target 50-80 words. HARD CAP 100 words - if you are about to exceed it, cut a sentence rather than let it run over, even if that means leaving out a nice-to-have elaboration. If the concept is small enough to explain correctly in 30, use 30 - do not pad to hit a target. Real exam-relevant depth means: the actual definition/mechanism, not a restatement of the label, and not a simplified version that would mislead at exam standard - depth comes from PRECISION (the exact mechanism, in the fewest words that state it correctly), never from adding a second example, a restated rephrasing of the same point, or a "to put it another way". State the point once, correctly, and stop.

1a. **Nod to a prerequisite for orientation - never derive this concept FROM one, or from several together.** A single short opening reference to this node's own most immediately relevant prerequisite, by name, is fine purely to orient the student ("Building on X, ..."). But do not construct this concept's actual justification by chaining or synthesizing prerequisites together ("because X, and because Y, therefore Z") - that is integration-level reasoning across concepts, and belongs in the edge lesson between this node and each of those prerequisites, not here. This node's explanation must still stand entirely on its own as the atomic definition/mechanism its own label names (rule 2) - a student who never saw the prerequisite at all should still come away with a complete, correct understanding of THIS concept from this text alone. Grounding is one sentence of orientation, not the argument itself.

1b. **Format for scanning, not solid prose.** Write the explanation as SHORT, SEPARATE lines - one sentence per paragraph, with a blank line between paragraphs (write the two characters backslash-n twice, i.e. a blank line, between them in the JSON string). Never run several sentences together into one block; a paragraph may hold a second sentence only when it cannot stand without the first. The definition (\"X = ...\") is always its own paragraph. When a sentence names several key points (e.g. what \"willing\" means and what \"able\" means), give EACH point its own paragraph instead of one long sentence. Example of the required shape (paragraphs shown one per line): \"Building on the assumption that firms aim to maximise profits, supply describes how much of a good those firms bring to market.\" / \"Supply = the quantity of a good or service that firms are willing and able to produce and sell at a given price, over a given time period.\" / \"The key words matter: willing means firms choose to offer it (it must be worth producing given costs and expected profit).\" / \"Able means they have the resources and capacity to actually produce it.\"  Bold the specific key terms and definitions a student actually needs to retain, using **term** markup, sparingly - individual words or short phrases only, never a whole sentence.

1d. **Whenever the content genuinely enumerates a set of discrete items - a stated number of things ("N types of X", "N factors that..."), a list of categories, a sequence of named steps - write that part as a REAL markdown list, not a paragraph.** A student skimming a dense sentence like "land (natural resources), labour (the workforce...), capital (machinery...), and enterprise (entrepreneurs...)" easily misses one item entirely mid-sentence; the same four items as their own lines cannot be skimmed past unnoticed. Use a plain asterisk-space bullet for a top-level statement (e.g. "* Finite resources = factors of production that exist in limited quantities"), then a numbered "1. " list directly under it for the enumerated items themselves (e.g. "1. Land = natural resources"), one line per item, each written as "name = its own one-line definition" using the same direct "X = Y" statement rule 1c already requires - never a bare name with no definition, and never the definition alone with no name. This is a FORMATTING change only, not a license to say less: each list item's definition must still carry the same genuine explanatory content rule 1 requires (the actual mechanism/meaning, in as few words as that takes) - a list of bare name-definition pairs with nothing connecting or explaining them starts reading like a flashcard deck rather than a taught concept, which this is not; keep whatever connecting sentence explains WHY these items belong together or what they collectively mean as its own short paragraph (via rule 1b) before or after the list, not folded into it. Content that ISN'T actually enumerable - a single flowing definition, one mechanism, a cause leading to an effect - stays as ordinary short paragraphs; don't force a list where nothing is genuinely being listed.

1e. **A vocabulary/term node gets the same one-term-per-line list treatment as rule 1d even at just one or two items - never flowing prose.** A node whose actual content IS a specific word/phrase paired with its meaning - including a single word, or a two-item contrastive/comparison pair - must not be written as "X means A, while Y means B"; write each term as its own list line, same "name = definition" format as rule 1d, even when the list has only one or two lines. This is exactly where it matters most: two short definitions run together in one sentence read as a single blurred idea, not two separately memorable words - rule 1d's own "isn't actually enumerable" exception is for a genuinely single flowing mechanism/definition, never for a node whose content is itself named term(s) being defined.

1f. **Language-learning subjects: HARD LIMIT of 2 items per lesson.** A lesson may teach at most TWO discrete items (words, phrases, pronouns, verb forms, endings) - never three or more, however the node's label is worded. Choose the two so they CONTRAST with each other (e.g. tu vs usted, masculine vs feminine, singular vs plural, ser vs estar forms), and make the explanation draw out that contrast in one line, since a contrasting pair is what makes two words stick. If the node's label names more than two items, teach ONLY the first two named and leave the rest out entirely - never list, summarise or foreshadow the others (they have their own lessons). No word lists, no full paradigms, no "etc." Keep the explanation to a couple of short lines.

1g. **One lesson is one quick card: the 100-word cap counts EVERYTHING, lists included, and there is a hard ceiling on how many items it may hold.** A student scrolls through these fast, so a card that packs in a list to memorise fails even when it is accurate. Limits, all of them binding, and checked by the app (a lesson over them is rejected and rewritten): at most FOUR list lines; at most FOUR "X = Y" definitions; at most ONE named case or statute citation with its year; about 100 words in all. If the label names more than four discrete items (five reforms, five limbs of a test, several cases), teach the idea that unites them plus the FOUR most exam-central items, and stop - never squeeze the rest in as fragments or a trailing "and also...", because the remaining items get their own cards. A card should be readable in about 30 seconds. Rule 4b's "test every item" applies only to the items this card actually taught.

1c. **State a definition directly - never wrap it in throat-clearing verbs.** Write "Utility is the satisfaction a consumer gains from consuming a good" or "Utility = satisfaction gained from consumption", never "Utility means that a consumer gains satisfaction when..." or "Utility refers to the concept of...". "X is Y" / "X = Y" states the fact; "X means that..." / "X refers to..." / "X can be understood as..." spends words restating that a definition is about to happen instead of just giving it. This applies throughout the explanation, not only its opening sentence - every definitional statement inside a longer paragraph gets the same direct treatment, not just the first one.

2. **Stay inside exactly what this node's own label asserts - do not reach for the "complete" textbook framing if part of that framing is really a separate idea.** A concept is often conventionally taught alongside neighbouring ideas (e.g. "economics as a social science" alongside "scarcity and the economic problem") - that doesn't mean this one node should explain or test both. If the label doesn't name it, leave it out, even if the explanation then reads as narrower than a textbook paragraph would. The graph's atomicity is only real if each node's own content actually stays atomic - a node that quietly re-teaches a neighbouring node's territory makes that neighbour's own lesson feel redundant, and makes this node's practice question test more than it was ever taught to test. The mark scheme especially must never require a point that belongs to a different concept's own definition.

3. **Never explain, hint at, or foreshadow the "leads to" concepts you were given.** Those connections are taught and TESTED separately, later, as a dedicated link-teaching step followed by a genuine transfer question that checks whether the student can make the connection themselves. If your explanation here already draws that connection, the transfer question becomes trivial - the student would be pattern-matching your own words back to you instead of demonstrating real understanding. Teach this node as if the concepts it leads to don't exist yet, because pedagogically, for this student, they don't.

4. **One practice question, testing this concept alone.** It must be answerable from this node's own explanation plus its own prerequisites - never from a "leads to" concept, and never requiring the student to already know a link this lesson hasn't taught. Write a real mark scheme: what specifically must the answer say to be marked correct (this app grades free-text answers as correct/incorrect only - no partial credit - so the mark scheme must draw an unambiguous line). The mark scheme must only require what the question you just wrote actually asks - never a point that's true and related but outside the question's own specific wording.

4a. **Decide how the practice question is genuinely answered.** Set "modality" to "reading" if answering requires comprehending written text, "writing" if it requires producing written text, "listening" if it requires comprehending SPOKEN language, or "speaking" if it requires producing spoken language. For a subject with no genuine spoken/heard component (true of most academic subjects), this is always "writing" - answering in text is the only way the concept is ever actually tested there, and there is no reason to reach for "reading"/"listening"/"speaking" just because the student happens to read the question or could imagine saying the answer aloud. Only a language-learning subject should ever produce "listening" or "speaking" - and only when the concept itself is fundamentally about comprehending or producing spoken language, not merely because the subject involves a spoken language in general. If "modality" is "listening", also set "audioText" to the exact phrase or sentence (in the language being learned) that should be played to the student and that the question is actually about - omit this field entirely for every other modality.

4a2. **Decide whether the practice question needs the maths keyboard.** Set "answerInputType" to "math" if a correct answer genuinely requires writing out a calculation, formula, or symbolic expression (the student answers using a maths-notation keyboard - fractions, surds, powers, etc. - not a plain textbox), or "words" if it's answered by explaining/defining/describing in prose, even if that prose mentions a number or quantity in passing. Choose "math" only when the answer itself IS the working/expression, not merely because the topic or subject is mathematical - a question asking "what is a fraction?" is "words" even in a maths subject; a question asking the student to actually simplify, solve, or evaluate something is "math" even if its wording never contains the word "calculate" (e.g. "Simplify √12", "Work out 5√2 + 3√2", "Solve x² = 3, giving your answer as a surd" are all "math"). This is independent of "modality" above - only ever set "math" when "modality" is "writing" (never "reading"/"listening"/"speaking", which have no numeric/symbolic answer at all). Omit this field entirely (or set "words") for a subject with no genuine calculation-style answers.

4b. **If this node's own label names a GROUP of closely related discrete items taught together (e.g. a set of vocabulary words, a family of forms/conjugations, a list of terms) rather than one single unified idea, the practice question must test EVERY item in the group, not just one.** A single item within a taught group (one pronoun out of "io/tu/lui/lei/noi/voi/loro", one verb form out of a conjugation set) is too small a thing to test alone - a student who only got asked about "noi" could be missing "loro" entirely and still pass. Phrase it as one fill-in-the-gaps question with a blank for every item in the group (e.g. "Fill in the missing subject pronoun for each: ___ mangio, ___ mangia, ___ mangiamo..." adapted to whatever the group actually is), never a word bank or multiple-choice list of options to fill the blanks from - the point is genuine recall of each item, and a word bank lets a student find the last blank or two by elimination rather than actually knowing them. The mark scheme must state the exact correct answer for every blank. This almost never applies outside a language-learning subject's vocabulary/grammar-form groups; a node that already names one single concept (true of most nodes, in every subject) has nothing to group and this rule simply doesn't apply to it.

4c. **Whenever rule 4b applies, ALSO populate "blanks" as an ordered array, one entry per blank, in the same order they appear in the question** - each entry is an object with "prompt" and "answer" string fields, where "prompt" is the short cue for that one blank alone (e.g. "___ mangio" or "I = ___", not the whole question) and "answer" is the single exact correct answer for that blank alone, matching the mark scheme exactly. This lets the app show one small answer box per blank instead of one big text box - never invent a "blanks" array for a question rule 4b doesn't apply to (a single free-text or calculation answer has nothing to split); omit the field entirely in that case.

4d. **For a language-learning subject, never write a mark scheme, "blanks" answer, or recall-check answer that requires an accent/diacritic mark to be typed correctly.** Students type on a standard English keyboard, which cannot produce accented characters (à, è, ì, ò, ù, é, ñ, ü, ç, etc.) without extra effort most don't know how to do - this app's own grading already treats the unaccented form as equivalent, so a mark scheme that says otherwise (e.g. "'si' without the accent is not acceptable for 'yes'") actively fights that leniency instead of working with it. State the correctly-accented spelling as the model answer (that's still what you're teaching), but never write language in the mark scheme itself that singles out the accent as required or disqualifying - if the concept genuinely IS the accent distinguishing two real words (e.g. Italian "sì"/"si", Spanish "sí"/"si"), teach that distinction in the explanation, but grade on the word/meaning conveyed, not the diacritic.

5. **No restated scaffolding, no throat-clearing, no "in this lesson you will learn."** Start with the actual content.

6. **Also write 4 short RECALL CHECKS** - lightweight re-tests of this SAME concept, used minutes later (same session) AND the day after (the Day-1 check draws from this identical pool) to check whether it actually stuck, not exam-depth questions. Each must test the identical concept this node's own label names, but with different specific numbers/wording/angle than "practiceQuestion" and than each other, so none of the 4 (or practiceQuestion) ever look like a literal repeat of another. Mix formats across the 4, in this exact order - "free_text" (a short free-text question, graded like "practiceQuestion" - write its own "markScheme"), "fill_blank" (ONE sentence with exactly one blank, testing a single specific fact/term/number, with a single exact expected "answer" - pick a blank where that one word/number is genuinely the natural, unambiguous way to complete the sentence, not a spot where several different words could equally fit; grading accepts a real synonym of your "answer" too, but write the sentence so the intended word is still the obvious one, not a coin-flip between two equally-valid terms), "multiple_choice" (a short question plus exactly 4 options, one correct, the other 3 real plausible mistakes for this concept specifically - never obviously-wrong filler - "correctOptionIndex" 0-3), then "free_text" again for the 4th (a different angle/example than the first). Every one must be answerable from this node's own explanation alone, same scope discipline as rule 2 - never reaching into a "leads to" concept.

6-scope. **A mark scheme may only require what its question actually asks for, read literally.** If a question gives a claim or premise (e.g. "infinite resources at zero cost"), the mark scheme must accept that premise as stated - never require the student to also question it, hedge it, or consider a weaker version of it ("what if it were only very large"). Any extra depth belongs in a clearly optional "Also acceptable" note, never in what is needed to be correct. Write the marking points a student would reasonably infer from the question's own wording.

6a. **Whenever rule 4b applies (this node's label names a GROUP of discrete items), every recall check that CAN cover the whole group must, not just one item at a time - the exact same reasoning as 4b, extended from the practice question to these checks and the Day-1 check too (it draws from this identical pool).** A recall that only re-quizzes one pronoun out of six leaves the other five's retention completely untracked between one full encoding and the next real spaced review days later - the whole point of a recall/Day-1 check is to catch a gap before it's forgotten, and a partial check can't do that for the items it never asks about. Both "free_text" checks and the "multiple_choice" check must each test every item: a "free_text" asks for every item's meaning/form in one answer (e.g. "Give the English meaning of each: come, dove, quando" - "markScheme" lists the correct pairing for every one; the two free_text checks still differ in angle from each other - e.g. one asks meaning-of-each, the other reverses the translation direction - even though both cover the full group), "multiple_choice" asks the student to pick the one option (out of 4 complete groupings/pairings) where EVERY item in the group is correctly matched - the other 3 options must each have at least one item wrong, never all-items-wrong filler - rather than asking about a single item in isolation. "fill_blank" is the one exception - it keeps rule 6's own single-blank, single-answer shape unchanged (this app's fill-blank UI is genuinely one blank), so rotate which single item it tests instead; between it and the other three checks (plus practiceQuestion), every item in the group still ends up genuinely tested somewhere every session.

## Output format

Return ONLY valid JSON:
{
  "explanation": "the teaching text",
  "practiceQuestion": { "questionText": "...", "markScheme": "what makes an answer correct, stated precisely enough to grade as correct/incorrect", "modality": "reading" | "writing" | "listening" | "speaking", "audioText": "the phrase to play, ONLY when modality is \"listening\" - omit otherwise", "answerInputType": "words" | "math", "blanks": [{ "prompt": "...", "answer": "..." }] },
  "recallChecks": [
    { "format": "free_text", "questionText": "...", "markScheme": "..." },
    { "format": "fill_blank", "questionText": "a sentence with one ___ blank", "answer": "the single exact expected answer" },
    { "format": "multiple_choice", "questionText": "...", "options": ["...", "...", "...", "..."], "correctOptionIndex": 0 },
    { "format": "free_text", "questionText": "...", "markScheme": "..." }
  ]
}
"blanks" ONLY when rule 4b applies - omit the field entirely otherwise. A recallCheck's "fill_blank" always keeps the single "answer" field shown above (see rule 6a) - it never takes a "blanks" array.`;

// Version 2 of the encoding lesson prompt, used for every subject except the languages and Biology (which keep their own
// rules and validation). Same rules up to 4a2, then: the practice question's FORMAT is chosen from the concept (free recall,
// spot the mistake, match, order; diagrams and maths keep their own paths), and only THREE questions are generated in all.
const V2_HEAD = KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT.slice(0, KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT.indexOf('4b. **If this node'));
const LANGUAGE_RULES = KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT
  .slice(KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT.indexOf('4b. **If this node'), KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT.indexOf('5. **No restated'))
  .replace(/rule 4b/g, 'rule L1').replace(/rule 4c/g, 'rule L2').replace('4b. **If this node', 'L1. **LANGUAGE SUBJECTS ONLY. If this node').replace('4c. **Whenever', 'L2. **Whenever').replace('4d. **For a language', 'L3. **For a language')
  + 'L4. **In a language subject the two recall checks must also cover every item of a group wherever their format allows** (a "fill_blank" tests one item, so rotate which one), and all of L3 applies to them.\n\n';
function buildV2(language: boolean): string {
  return V2_HEAD + `4a3. **Every question must be answerable from your own explanation, and only from it.** Every fact a mark scheme requires, and every item in an interactive question's key, must be stated in the explanation you write, in words a student could point to. Never test how something is implemented, applied, enforced or extended unless the explanation itself teaches it. Before you finish, check each mark-scheme point against the explanation: if one is missing, change the question (do not add extra chunks to the explanation).

4b. **Choose the FORMAT of the practice question from what this concept actually is.** Set "format" to one of:
- "free_text": ONLY for a calculation or worked method (set "answerInputType" to "math"; a calculation is never one of the interactive formats below). Never use it for anything else, in the practice question or in a recall check: open recall is asked later by the app itself, at spaced reviews. A concept that is just a term and its definition uses "cloze" (blank the term in its definition) or "fill_blank". A concept whose whole point is the SHAPE or movement of a curve or diagram (supply and demand, cost and revenue curves, AD/AS and the like) is written as any interactive format: the app turns it into a draw-the-diagram question by itself.
- "spot_mistake": use it when a concept has a tempting misconception, or a rule that is easy to misstate. The wrong sentence must be PLAUSIBLE: a real slip a student would make (a swapped term, a wrong number, a reversed relationship, a missing condition). NEVER give it away with an extreme word such as "never", "always", "all", "only", "regardless" or "impossible". It is NOT a default: use it at most ONCE across the practice question and the two recall checks, and prefer "order" for processes and sequences, "match" for sets of terms, cases or types, and "fill_blank" or "multiple_choice" for a single fact. Write "segments": 4 to 6 short sentences that read as one connected explanation or application of the concept, exactly ONE of which contains a plausible mistake of the kind a real student makes (never an absurd or obviously silly one). Give "errorIndex" (0-based position of the wrong sentence) and "correction" (one or two sentences saying what is wrong and what is right). The "questionText" is a short instruction such as "One sentence here is wrong. Tap it." and must not point at the sentence.
${language ? "- \"match\" is NOT available in a language subject: a language lesson holds at most two items, and a match needs three to five. Use \"spot_mistake\" (a short target-language sentence or exchange in which exactly one word or form is wrong) or \"order\" (the words of one sentence, in the correct order, to be put back in order) when they suit the item better than plain recall or the grouped fill-in-the-gaps question below." : '- "match": use it when the concept is a small set of 3 to 5 items each paired with something (terms with definitions, named cases with the principle each established, types with examples, causes with consequences). Give "pairs": [{"left": "...", "right": "..."}], where every "right" is distinct and fits ONLY its own "left". The "questionText" says what is to be matched to what. On a recall check add "decoys": 1 or 2 extra wrong "right" pieces that look plausible for this concept but match nothing.'}
- "order": use it when the concept is a process, procedure, sequence of stages or chain of cause and effect. Give "items": 3 to 6 short steps (under 12 words each) listed in the CORRECT order. The "questionText" says what is to be ordered but does not list the steps. On a recall check add "decoys": 1 to 3 plausible but wrong extra steps that belong nowhere in the sequence.
- "cloze": the student TYPES the missing terms. Give "text": one to three connected sentences that state the idea with "___" where each key term or number goes, and "blanks": [{"answer": "...", "alt": ["accepted synonyms"]}] with exactly one entry per "___" (2 to 6). Blank out the terms a student must be able to produce, never small words.
- "steps" (a recall-check format): the student TYPES the steps of a process in order, one per line. Give "steps": 3 to 6 objects {"text": "the step", "keys": ["2 to 4 short words or phrases, any one of which a correct line must contain"]}. Use it for processes and sequences, alongside or instead of "order".
Pick the format that genuinely tests this concept, never one merely for variety. Whatever the format, still write a "markScheme": one or two plain sentences stating the correct answer. Every interactive format must be answerable from this node's own explanation alone.

${language ? LANGUAGE_RULES : ""}5. **No restated scaffolding, no throat-clearing, no "in this lesson you will learn."** Start with the actual content.

6. **Also write exactly 2 short RECALL CHECKS** - lightweight re-tests of this SAME concept, used minutes later (same session), the day after (the Day-1 check draws from this same pool) and again in spaced review, where the app rotates through the practice question and these two. Each must test the identical concept this node's own label names, from a different angle and with different specifics than "practiceQuestion" and than each other, so none ever looks like a literal repeat. Choose each one's format to suit the concept, from: "fill_blank" (ONE sentence with exactly one blank testing a single fact, term or number, with one exact expected "answer" that is the obvious way to complete it), "multiple_choice" (a short question plus exactly 4 options, one correct, the other 3 real plausible mistakes for this concept - "correctOptionIndex" 0-3), or one of the interactive formats "spot_mistake", "match" or "order" in the same shape as rule 4b. Across the practice question and the two recall checks use THREE DIFFERENT formats wherever the concept allows (never two "spot_mistake" questions, and never the same interactive format twice), so the questions a student meets over time differ from one another; never repeat a format just because it is convenient. The recall checks are DELAYED retrieval, so they must make the student PRODUCE the answer, not merely recognise it. At least ONE of the two must be typed ("cloze", "steps" or "fill_blank"), and any "order" or "match" recall check must carry "decoys". Never use "free_text" for a recall check: open recall is asked later by the app itself. Never both "fill_blank" and "multiple_choice"; the Day-1 check can only ask "cloze", "steps", "spot_mistake", "match" or "order". Every one must be answerable from this node's own explanation alone, same scope discipline as rule 2.

6-scope. **A mark scheme may only require what its question actually asks for, read literally.** If a question gives a claim or premise (e.g. "infinite resources at zero cost"), the mark scheme must accept that premise as stated - never require the student to also question it, hedge it, or consider a weaker version of it. Any extra depth belongs in a clearly optional "Also acceptable" note, never in what is needed to be correct.

## Output format

Return ONLY valid JSON:
{
  "explanation": "the teaching text",
  "practiceQuestion": { "format": "free_text" | "spot_mistake" | "match" | "order", "questionText": "...", "markScheme": "...", "modality": "writing", "answerInputType": "words" | "math", ${language ? '"blanks": [{ "prompt": "...", "answer": "..." }], ' : ""}"segments": ["..."], "errorIndex": 0, "correction": "...", "pairs": [{ "left": "...", "right": "..." }], "items": ["..."], "decoys": ["..."], "text": "...___...", "blanks": [{ "answer": "...", "alt": ["..."] }], "steps": [{ "text": "...", "keys": ["..."] }] },
  "recallChecks": [
    { "format": "free_text" | "fill_blank" | "multiple_choice" | "spot_mistake" | "match" | "order" | "cloze" | "steps", "questionText": "...", "markScheme": "..." },
    { "format": "free_text" | "fill_blank" | "multiple_choice" | "spot_mistake" | "match" | "order" | "cloze" | "steps", "questionText": "...", "markScheme": "..." }
  ]
}
Include ONLY the fields that belong to the chosen format ("segments", "errorIndex" and "correction" for spot_mistake; "pairs" (and optional "decoys") for match; "items" (and optional "decoys") for order; "text" and "blanks" for cloze; "steps" for steps; "answer" for fill_blank; "options" and "correctOptionIndex" for multiple_choice). Omit every other format-specific field.`
}

export const KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT_V2 = buildV2(false);
export const KNOWLEDGE_MAP_ENCODING_LESSON_PROMPT_V2_LANG = buildV2(true);

export const KNOWLEDGE_MAP_EDGE_LESSON_PROMPT = `You are writing the LINK-TEACHING and testing content for one prerequisite edge in a subject's knowledge-map graph, run after both A and B have already had their own separate encoding lessons. You will be given the subject, qualification, exam board, subtopic, A's label and explanation, and B's label and explanation.

FIRST decide which of two genuinely different jobs this edge actually has, based on the subject and on what A and B actually are:

- **CONCEPTUAL** (the default - true for essentially all non-language subjects, and for a language subject's own genuinely conceptual edges, e.g. grammar rules that build on each other): explain why understanding concept A is genuinely necessary before concept B makes sense - a real dependency, not just "these were taught near each other." Your job is to teach the CONNECTION, not either concept again, then test it twice - once as transfer, once as integration. See rules 1-3 below.
- **COMBINATORIAL** (ONLY for a language-learning subject, and only when A and B are vocabulary items, phrases, or grammatical forms whose real relationship is that they're used TOGETHER in speech/writing, not that one is conceptually required to understand the other - e.g. a verb and an object noun, a subject pronoun and a conjugated verb form, two phrases that commonly combine): there is no real "why is A necessary for B" claim to make here, and forcing one produces exactly the kind of philosophical-sounding but hollow reasoning this rule exists to avoid. Instead, teach and test genuinely COMBINING A and B into natural language use. See rules 1c-3c below.

## Rules — CONCEPTUAL edges

1. **Teach only the bridge.** Target 40-60 words, HARD CAP 80. Do not re-explain A or B's own definitions - the student already has both from their own encoding lessons. State specifically why A is required for B: what would break, or fail to make sense, about B without A. One clear sentence stating the bridge is often enough - do not add a second sentence restating it or illustrating it again unless it adds a genuinely new point.

2. **The transfer question tests whether the student can apply A in a new situation involving B - not recall your link-teaching text back.** It must require genuinely using both concepts together to answer, phrased with different specifics than the link-teaching explanation used (a new example, a new number, a new context) so a student who only memorised your wording cannot pattern-match their way to a correct answer. Write a precise mark scheme (correct/incorrect only, no partial credit).

## Rules — COMBINATORIAL edges (language-learning only)

1c. **Teach how A and B combine in real use.** Target 40-60 words, HARD CAP 80. Do not re-explain A or B's own individual meanings - the student already has both. Show, with at least one genuine example, how they actually go together (word order, agreement, a grammatical pattern) - what a correct combination looks like and what commonly goes wrong (a typical agreement/order mistake) if that's genuinely relevant.

2c. **The transfer question asks the student to construct a natural phrase or sentence that correctly uses BOTH A and B together** - not to explain a relationship, and not to recall the link-teaching example verbatim (use a different concrete scenario/subject/object than the link-teaching text did). Grade it on correct combination (word order, agreement, the specific pattern this edge teaches), not on prose reasoning. Write a precise mark scheme naming exactly what a correct combination must contain.

3c. **The integration question asks for a SECOND, more demanding combination of A and B** - a longer or more naturally-phrased sentence, an added twist (negation, a question form, a different tense/register) that still requires both A and B correctly combined - assume it is only ever shown to a student who already passed the transfer question. Write a precise mark scheme naming exactly what a correct combination must contain, the same way as 2c.

## Rules — both kinds of edge

2a. **Decide how the transfer question is genuinely answered** - same "modality"/"audioText" decision as the encoding lesson's practice question (reading/writing for most academic subjects, listening/speaking only for a language-learning subject and only when the concept itself is fundamentally about comprehending or producing spoken language). For a COMBINATORIAL edge this is very often "speaking" or "writing" (producing the combined phrase), rarely "reading"/"listening".

3. **Non-language subjects only, for the integration question**: it tests the same connection at slightly greater depth or in a further-transformed context - assume it is only ever shown to a student who has already passed the transfer question, so it does not need to re-establish the basics, but it must still be answerable from A, B, and the link alone (no smuggled-in third concept). Write a precise mark scheme, and decide its own "modality"/"audioText" the same way as rule 2a.

3a. **Decide whether the integration question needs the maths keyboard.** Set "answerInputType" to "math" if a correct answer genuinely requires writing out a calculation, formula, or symbolic expression (the student answers using a maths-notation keyboard, not a plain textbox) - or "words" if it's answered by explaining the connection/reasoning in prose, even if that prose mentions numbers or a quantity in passing (always "words" for a COMBINATORIAL edge - constructing a phrase is never a maths-keyboard answer). Choose "math" only when the answer itself IS the working/expression, not merely because the topic is mathematical. This is independent of "modality" above - a "speaking" question is always answered in words, never via this maths keyboard, so only set "answerInputType" when "modality" is "reading" or "writing".

4. **No restated scaffolding, no throat-clearing.** Start with the actual content.

5. **State the connection directly, the same way the encoding lesson states a definition directly.** "A requires B because..." / "A determines B by...", never "The relationship between A and B can be understood as..." or "This link means that...". Say the actual bridge, not that a bridge is about to be described.

## Output format

Return ONLY valid JSON:
{
  "linkTeaching": "the bridge explanation",
  "transferQuestion": { "questionText": "...", "markScheme": "...", "modality": "reading" | "writing" | "listening" | "speaking", "audioText": "ONLY when modality is \"listening\"" },
  "integrationQuestion": { "questionText": "...", "markScheme": "...", "modality": "reading" | "writing" | "listening" | "speaking", "audioText": "ONLY when modality is \"listening\"", "answerInputType": "words" | "math" }
}`;
