// Hand-authored (no API calls) fix for stage 53 - the same fallback bug as Great Divergence: this stage had never
// been successfully generated by the live pipeline, so the student got the old "teachingCards" fallback lesson
// (titled "A new source of wealth") instead of the mechanistic derivation format. Real stage index confirmed by
// running plan_stages.js's plan() locally against the live graph (see the investigation this follows).
//
// Also the first use of the new 'explain' step type: this stage's payoff is a causal comparison (why Atlantic
// trade strengthened parliament in England but absolutism in Spain) and an evaluative synthesis (weighing three
// rival theories against each other) - both suit writing an answer far better than dragging labels into boxes, so
// this stage ends on 'explain' instead of the usual drag-and-drop 'derive' puzzle, per direct instruction to vary
// the ending rather than defaulting to the same interaction every time.
require('dotenv/config');
const { createClient } = require('@supabase/supabase-js');
const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const SUBJECT = 'Economics', QUALIFICATION = 'Undergraduate Year 1', EXAM_BOARD = 'Warwick';
const LINK = 'economics:ec104_early_modern_period:atlantic_trade_as_a_driver_of_institutional_change';
const EVAL = 'economics:ec104_early_modern_period:evaluating_institutional_vs_geographic_vs_cultural_explanations_of_divergence';
const GD = 'economics:ec104_early_modern_period:the_great_divergence_question_why_europe_';
const INST = 'economics:ec104_early_modern_period:institutional_explanations_for_economic_development_property_rights_constraints_on_rulers_';
const GEO = 'economics:ec104_early_modern_period:geographic_explanations_for_divergence_resources_disease_climate_';
const CULT = 'economics:ec104_early_modern_period:cultural_ideational_explanations_for_divergence_values_religion_science_';
const GLOR = 'economics:ec104_early_modern_period:case_study_england_s_glorious_revolution_1688_and_credible_commitment';
const AT = 'economics:ec104_early_modern_period:atlantic_trade_and_colonial_expansion';

const ROW_H = 64, GAP = 40, MARGIN = 20;
// 5 given (already-taught) nodes feed into LINK and EVAL - laid out as a left column of given nodes flowing into
// the two new nodes on the right, positions/edges computed the same programmatic way as the Great Divergence fix.
const givenY = [0, 1, 2, 3, 4].map((i) => MARGIN + i * (ROW_H + GAP));
const nodes = {
  [GD]: [20, givenY[0], 210, ROW_H],
  [INST]: [20, givenY[1], 210, ROW_H],
  [GEO]: [20, givenY[2], 210, ROW_H],
  [CULT]: [20, givenY[3], 210, ROW_H],
  [AT]: [20, givenY[4], 210, ROW_H],
  [GLOR]: [20, givenY[4] + ROW_H + GAP, 210, ROW_H],
  [LINK]: [340, Math.round((givenY[1] + givenY[4]) / 2), 260, ROW_H],
  [EVAL]: [700, Math.round((givenY[1] + givenY[4]) / 2), 300, ROW_H],
};
const totalH = Math.max(...Object.values(nodes).map(([, y, , h]) => y + h)) + MARGIN;
const midRight = (id) => { const [x, y, w, h] = nodes[id]; return [x + w, y + h / 2]; };
const midLeft = (id) => { const [x, y, w, h] = nodes[id]; return [x, y + h / 2]; };
function elbow(fromId, toId) {
  const [fx, fy] = midRight(fromId), [tx, ty] = midLeft(toId);
  if (Math.abs(fy - ty) < 4) return [[fx, fy], [tx, ty]];
  const midX = fx + (tx - fx) / 2;
  return [[fx, fy], [midX, fy], [midX, ty], [tx, ty]];
}
const pairs = [[INST, LINK], [AT, LINK], [GLOR, EVAL], [CULT, EVAL], [INST, EVAL], [LINK, EVAL]];
const edges = pairs.map(([a, b]) => elbow(a, b));

const compiled = {
  i: 53,
  name: [LINK, EVAL].join(','),
  edges: [[LINK, EVAL]],
  nodes: [LINK, EVAL],
  stage: {
    hud: 'Stage 53 · Atlantic trade, institutions, and the verdict on divergence',
    sub: 'After this you can explain how Atlantic trade’s effect on institutions depended on what was already there, and weigh the three rival theories against each other.',
    name: 'Atlantic trade, institutions, and the verdict on divergence',
    given: [GD, INST, GEO, CULT, AT, GLOR],
    graph: { h: totalH, edges, given: [GD, INST, GEO, CULT, AT, GLOR], nodes, pairs },
    title: 'Atlantic trade, institutions, and the verdict on divergence',
    builds: [GD, INST, GEO, CULT, AT, GLOR],
    script: [
      { type: 'title' },
      {
        q: 'In England, merchants grown rich from Atlantic trade allied with an already-strong parliament to demand stronger property rights. In Spain, an already-absolute monarchy simply monopolised the trade profits directly. Did Atlantic trade produce the SAME institutional outcome in both countries?',
        ok: 0,
        pre: 'This shows Atlantic trade acting as',
        hint: 'The trade was the same kind of activity in both places - what differed was what it fed into.',
        opts: ['No - it reinforced whatever institutions were already there', 'Yes - trade always produces the same institutional effect'],
        term: LINK, type: 'ask',
      },
      {
        type: 'explain',
        term: EVAL,
        title: 'Explain it yourself',
        prompt: 'In your own words: what is the key weakness of EACH of the three explanations for the Great Divergence (institutional, geographic, cultural) - and why do most historians now favour combining them rather than picking just one?',
        model: "The institutional explanation struggles with timing: England's constraints on its rulers existed decades before industrial takeoff actually began, so institutions alone don't explain WHEN growth started. The geographic explanation has a circularity problem: coal only became valuable once industrial demand for it already existed, so citing coal as the cause of industrialisation risks putting the effect before the cause. The cultural explanation is hardest to test rigorously, since values and attitudes are difficult to measure or compare directly against the alternatives. Because each theory alone leaves a real gap, most historians today favour multi-causal accounts that combine institutions, geography and trade together, rather than crediting any single factor.",
      },
      { type: 'done' },
    ],
  },
  terms: {
    [GD]: { c: '#cfd9e8', t: 'The Great Divergence' },
    [INST]: { c: '#f6ecb9', t: 'Institutional theory (North; Acemoglu & Robinson)' },
    [GEO]: { c: '#cfe3f6', t: 'Geographic/resource theory (Pomeranz; Allen)' },
    [CULT]: { c: '#f8d9c4', t: "Cultural theory (Weber's Protestant Ethic)" },
    [AT]: { c: '#cfd9e8', t: 'Atlantic trade and colonial expansion' },
    [GLOR]: { c: '#cfe8c8', t: "England's Glorious Revolution (1688)" },
    [LINK]: { c: '#e6c9a8', t: 'Atlantic trade as a driver of institutional change' },
    [EVAL]: { c: '#d9c9e6', t: 'Evaluating the three theories of divergence' },
  },
  concepts: [LINK, EVAL],
};

async function main() {
  const { error } = await db.from('derivation_generated_stages').upsert([{
    subject: SUBJECT, qualification: QUALIFICATION, exam_board: EXAM_BOARD, stage_index: 53, concept_ids: [LINK, EVAL], compiled,
  }], { onConflict: 'subject,qualification,exam_board,stage_index' });
  if (error) throw error;
  console.log('Stage 53 inserted. Total graph height:', totalH);
}
main().catch((e) => { console.error(e); process.exit(1); });
