// One-off, hand-authored content patch (NO Claude API calls) fixing two reported quality issues:
// 1. Stage 32 (Great Divergence cluster) was never successfully generated by the live pipeline, so students got
//    the OLD per-node fallback instead of a real derivation stage. Hand-authoring it directly at the exact stage
//    index plan_stages.js computes for these concepts (verified by actually running plan() locally - see the
//    investigation this patch follows from) means the live lookup finds this cached row and never falls back or
//    regenerates. Named scholars/works and real dates added throughout, since a non-mechanistic, comparative-
//    theory concept doesn't need (and box-checking wouldn't add) forced multiple-choice "ask" steps - it needs
//    real content, so this leans on the 'read' step type the schema already supports but the live generation run
//    never used here.
// 2. Stage 13 (EC140 calculus) jumped straight from title into quiz questions with zero explanation of what a
//    partial derivative IS or why it matters economically - added 'read' steps in front of the existing 'ask'
//    steps for the two most conceptually loaded terms.
require('dotenv/config');
const { createClient } = require('@supabase/supabase-js');
const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const SUBJECT = 'Economics', QUALIFICATION = 'Undergraduate Year 1', EXAM_BOARD = 'Warwick';

const GD = 'economics:ec104_early_modern_period:the_great_divergence_question_why_europe_';
const INST = 'economics:ec104_early_modern_period:institutional_explanations_for_economic_development_property_rights_constraints_on_rulers_';
const GEO = 'economics:ec104_early_modern_period:geographic_explanations_for_divergence_resources_disease_climate_';
const CULT = 'economics:ec104_early_modern_period:cultural_ideational_explanations_for_divergence_values_religion_science_';
const GLOR = 'economics:ec104_early_modern_period:case_study_england_s_glorious_revolution_1688_and_credible_commitment';

const stage32 = {
  subject: SUBJECT, qualification: QUALIFICATION, exam_board: EXAM_BOARD, stage_index: 32,
  concept_ids: [GD, INST, GEO, CULT, GLOR],
  compiled: {
    i: 32,
    name: [GD, INST, GEO, CULT, GLOR].join(','),
    edges: [[GD, INST], [GD, GEO], [GD, CULT], [INST, GLOR]],
    nodes: [GD, INST, GEO, CULT, GLOR],
    stage: {
      hud: 'Stage 32 · The Great Divergence debate',
      sub: 'After this you can name the three competing explanations for why Europe industrialised first, and a real historical test case for one of them.',
      name: 'The Great Divergence debate',
      given: [],
      graph: {
        h: 340,
        edges: [
          [[270, 72], [300, 72], [300, 40], [330, 40]],
          [[270, 72], [300, 72], [300, 168], [330, 168]],
          [[270, 72], [300, 72], [300, 296], [330, 296]],
          [[560, 72], [590, 72], [590, 220], [40, 220], [40, 256], [330, 256]],
        ],
        given: [],
        nodes: {
          [GD]: [40, 40, 230, 64],
          [INST]: [330, 8, 260, 64],
          [GEO]: [330, 136, 260, 64],
          [CULT]: [330, 264, 260, 64],
          [GLOR]: [330, 340, 300, 80],
        },
        pairs: [[GD, INST], [GD, GEO], [GD, CULT], [INST, GLOR]],
      },
      title: 'The Great Divergence debate',
      builds: [],
      script: [
        { type: 'title' },
        {
          type: 'read', term: GD,
          text: "Economic historians Kenneth Pomeranz and Robert Allen frame a puzzle: around 1700, Qing China's Yangtze Delta had living standards, markets and technology broadly comparable to Britain's - yet only Britain broke into sustained growth over the next century. This puzzle is",
        },
        {
          type: 'read', term: INST,
          text: "Douglass North, and more recently Daron Acemoglu and James Robinson, argue Britain diverged because it built institutions that constrained rulers and secured property rights, encouraging investment. This is the",
        },
        {
          type: 'read', term: GEO,
          text: "Kenneth Pomeranz's 2000 book 'The Great Divergence' argues Britain's cheap, geographically convenient coal and access to New World land let it escape resource limits that bound China's Yangtze Delta; Robert Allen separately stresses Britain's unusually high wages, which made machines that saved labour worth inventing. Together these form the",
        },
        {
          type: 'read', term: CULT,
          text: "Max Weber's 'Protestant Ethic' thesis links Reformation-era religious values to capitalist discipline and reinvestment, while others point instead to the Scientific Revolution's culture of open experimentation. Together these are the",
        },
        {
          done: 'Four candidate explanations locked in - one puzzle, three competing theories.',
          type: 'order',
          order: [GD, INST, GEO, CULT],
          pairs: [[GD, INST], [INST, GEO], [GEO, CULT]],
          title: 'Milestone: the puzzle and its three theories',
          prompt: 'Drag and drop the 4 terms in the order they were introduced above.',
        },
        {
          type: 'read', term: GLOR,
          text: "England's 1688 Glorious Revolution replaced an absolutist king with a parliament that could credibly commit not to expropriate merchants' assets - historians treat this as a real historical test of the institutional theory just covered. This episode is",
        },
        { type: 'derive', title: 'Final test: the whole derivation', prompt: 'Drag and drop the 5 key terms into the boxes to rebuild the whole derivation from memory. Chains meet at the concept.' },
        { type: 'done' },
      ],
    },
    terms: {
      [GD]: { c: '#cfd9e8', t: 'The Great Divergence', syn: ['Great Divergence puzzle'] },
      [INST]: { c: '#f6ecb9', t: 'Institutional theory (North; Acemoglu & Robinson)', syn: ['institutional explanation'] },
      [GEO]: { c: '#cfe3f6', t: 'Geographic/resource theory (Pomeranz; Allen)', syn: ['geographic explanation', "Pomeranz's coal thesis"] },
      [CULT]: { c: '#f8d9c4', t: "Cultural theory (Weber's Protestant Ethic)", syn: ['cultural explanation'] },
      [GLOR]: { c: '#cfe8c8', t: "England's Glorious Revolution (1688)", syn: ['Glorious Revolution case study'] },
    },
    concepts: [GD, INST, GEO, CULT, GLOR],
  },
};

const PD = 'economics:ec140_calculus_of_functions_of_two_or_more_variables:partial_derivatives_first_order_';
const TOTDIFF = 'economics:ec140_calculus_of_functions_of_two_or_more_variables:total_differential';

async function patchStage13() {
  const { data: row, error } = await db.from('derivation_generated_stages').select('*')
    .eq('subject', SUBJECT).eq('qualification', QUALIFICATION).eq('exam_board', EXAM_BOARD).eq('stage_index', 13).maybeSingle();
  if (error) throw error;
  if (!row) { console.warn('Stage 13 not found - skipping patch (nothing to fix yet).'); return; }
  const script = row.compiled.stage.script;
  const insertReadBefore = (term, text) => {
    const idx = script.findIndex((s) => s.term === term && s.type === 'ask');
    if (idx === -1) { console.warn('Could not find ask step for', term); return; }
    if (script[idx - 1] && script[idx - 1].type === 'read' && script[idx - 1].term === term) return; // already patched
    script.splice(idx, 0, { type: 'read', term, text });
  };
  insertReadBefore(PD,
    "In economics we constantly ask how output changes if ONE input changes while everything else is held fixed - e.g. the extra output from hiring one more worker, with capital unchanged. That rate of change with respect to a single variable, treating every other variable as a constant, is a");
  insertReadBefore(TOTDIFF,
    "Real changes rarely hold everything else fixed - labour and capital often move together. Adding each partial derivative multiplied by its own small change gives a first-order approximation of the resulting total change in output: the");
  const { error: upErr } = await db.from('derivation_generated_stages').update({ compiled: row.compiled }).match({ subject: SUBJECT, qualification: QUALIFICATION, exam_board: EXAM_BOARD, stage_index: 13 });
  if (upErr) throw upErr;
  console.log('Stage 13 patched: added 2 explanatory read steps.');
}

async function main() {
  const { error } = await db.from('derivation_generated_stages').upsert([stage32], { onConflict: 'subject,qualification,exam_board,stage_index' });
  if (error) throw error;
  console.log('Stage 32 (Great Divergence) inserted.');
  await patchStage13();
}
main().catch((e) => { console.error(e); process.exit(1); });
