const assert = require('node:assert/strict');
const { validate } = require('./build_aqa_biology_map');
const map = require('../src/data/aqaBiologyHigher.json');
const { getBiologyObjective, biologyNodeOrder, biologySourceContext, validateBiologyEncodingLesson } = require('../dist/services/biologyCurriculum');
const report = validate(map);
const sources = require('./aqa_biology_8461_sources.json');
const headings = [...new Set(sources.sources.flatMap(s => [...s.text.matchAll(/^4\.\d+\.\d+(?:\.\d+)?(?= )/gm)].map(m=>m[0])))];
const leaves = headings.filter(h=>!headings.some(other=>other.startsWith(h+'.')));
const covered = new Set(map.nodes.flatMap(n=>n.specRefs));
assert.ok(leaves.every(h=>covered.has(h)), 'Unmapped specification section: '+leaves.filter(h=>!covered.has(h)).join(', '));
assert.equal(report.roots.length, 5);
assert.ok(report.roots.every(r => map.nodes.find(n => n.id === r.id).rootReason));
assert.equal(new Set(map.nodes.map(n => n.label)).size, map.nodes.length);
const rank = new Map(map.nodes.map((n, i) => [n.id, i]));
assert.ok(map.edges.every(e => rank.get(e.from) < rank.get(e.to)), 'Published node order must respect every prerequisite');
assert.ok(map.edges.filter(e => map.nodes[rank.get(e.from)].theme !== map.nodes[rank.get(e.to)].theme).length > 100);
for (let p = 1; p <= 10; p++) {
  const practical = map.nodes.filter(n => n.practicalIds.includes(p));
  assert.ok(practical.some(n => n.kind === 'procedure'), `RP${p} lacks procedure`);
  assert.ok(practical.some(n => n.kind === 'application'), `RP${p} lacks interpretation`);
  assert.ok(practical.some(n => n.kind === 'evaluation'), `RP${p} lacks method evaluation`);
}
const hasEdge = (from, to) => map.edges.some(e => e.from === from && e.to === to);
for (const [from, to] of [['respiration','active_transport'], ['antibody','monoclonal'], ['p_zone','a_zone_area'], ['antibiotic','a_zone_area'], ['p_blot','e_blot'], ['p_endpoint','a_amylase_rate'], ['amylase','a_amylase_rate']]) assert.ok(hasEdge(from,to), `Missing essential dependency ${from}->${to}`);
assert.ok(hasEdge('plant_hormone','auxin'));
assert.ok(!hasEdge('hormone','auxin'), 'Plant hormones must not depend on animal blood-borne endocrine signalling');
const objective = getBiologyObjective({ subject: 'Biology', qualification: 'GCSE Higher', exam_board: 'AQA', label: map.nodes.find(n => n.id === 'osmosis').label });
assert.ok(objective);
assert.equal(getBiologyObjective({ subject: 'Biology', qualification: 'GCSE Foundation', exam_board: 'AQA', label: objective.label }), undefined);
assert.match(biologySourceContext(objective), /Osmosis/);
const question = { questionText: 'Describe osmosis, including its direction and membrane requirement.', markScheme: 'Require water, dilute to concentrated solution and a partially permeable membrane.', testedPointIds: ['water','direction','membrane'] };
const lesson = { atomicConceptId: objective.id, explanation: 'Osmosis is net movement of water from a dilute solution to a more concentrated solution through a partially permeable membrane.', taughtPoints: [{id:'water',text:'Water moves.'},{id:'direction',text:'Dilute to concentrated solution.'},{id:'membrane',text:'Through a partially permeable membrane.'}], practiceQuestion: question, recallChecks: Array.from({length:4}, () => ({ ...question, format:'free_text' })) };
validateBiologyEncodingLesson(lesson, objective);
assert.throws(() => validateBiologyEncodingLesson({...lesson, practiceQuestion:{...question,testedPointIds:['water']}}, objective), /omits/);
assert.throws(() => validateBiologyEncodingLesson({...lesson, taughtPoints:Array.from({length:5}, (_,i)=>({id:String(i),text:'New point'}))}, objective), /ceiling/);
assert.throws(() => validateBiologyEncodingLesson({...lesson, explanation:Array(102).fill('word').join(' ')}, objective), /100 words/);
assert.throws(() => validateBiologyEncodingLesson({...lesson, atomicConceptId:'other'}, objective), /wrong atomic/);
assert.throws(() => validateBiologyEncodingLesson({...lesson, recallChecks:[{...question,format:'free_text',testedPointIds:['water']},...lesson.recallChecks.slice(1)]}, objective), /omits/);
const reverse = map.nodes.slice(0,12).reverse().map(n=>({id:n.id,label:n.label}));
assert.deepEqual(biologyNodeOrder(reverse), map.nodes.slice(0,12).map(n=>n.id));
assert.throws(() => validate({nodes:map.nodes,edges:[...map.edges,{from:'active_transport',to:'respiration',difficulty:0.5}]}), /Cycle/);
assert.throws(() => validate({nodes:map.nodes,edges:[...map.edges,{from:'missing',to:'cell',difficulty:0.5}]}), /Dangling/);
console.log(`PASS: ${map.nodes.length} nodes; ${map.edges.length} acyclic ordered edges; all 10 practicals; cross-topic dependencies; Higher-tier isolation; complete recall coverage and four-point ceiling.`);
