'use strict';
const { V, R } = require('./helpers');

// A1.2 Numbers, days, months, seasons, time and age
module.exports = {
  NUM_0_20: V('zero=0; uno=1'),
  NUM_0_20__2: V('due=2; tre=3'),
  NUM_0_20__3: V('quattro=4; cinque=5'),
  NUM_0_20__4: V('sei=6; sette=7', ['Sei also means “you are”, as you will see later. Here it is the number 6.']),
  NUM_0_20__5: V('otto=8; nove=9'),
  NUM_0_20__6: V('dieci=10; undici=11'),
  NUM_0_20__7: V('dodici=12; tredici=13'),
  NUM_0_20__8: V('quattordici=14; quindici=15'),
  NUM_0_20__9: V('sedici=16; diciassette=17'),
  NUM_0_20__10: V('diciotto=18; diciannove=19'),
  NUM_0_20__11: V('venti=20'),
  NUM_21_100: V('venti=20; trenta=30'),
  NUM_21_100__2: V('quaranta=40; cinquanta=50'),
  NUM_21_100__3: V('sessanta=60; settanta=70'),
  NUM_21_100__4: V('ottanta=80; novanta=90'),
  NUM_21_100__5: V('cento=100'),
  NUM_21_100__6: V('ventuno=21; ventidue=22; ventitré=23', ['To make 21 to 99, say the tens word and then the unit: venti + due = ventidue.', 'The tens word loses its last vowel before uno and otto: ventuno, ventotto.', 'When tre ends the number it takes an accent: ventitré.'], { say: [['How do you say “21”?', 'ventuno'], ['How do you say “22”?', 'ventidue'], ['How do you say “23”?', 'ventitré']] }),
  NUM_ABOVE_100: V('cento=100; duecento=200', ['Hundreds are built as number + cento: trecento is 300 and quattrocento is 400.']),
  NUM_ABOVE_100__2: V('mille=1000', ['For more than one thousand, mille becomes mila: duemila is 2000.']),
  DAYS_OF_WEEK: V('lunedì=Monday; martedì=Tuesday', ['Italian days of the week start with a small letter, not a capital.']),
  DAYS_OF_WEEK__2: V('mercoledì=Wednesday; giovedì=Thursday'),
  DAYS_OF_WEEK__3: V('venerdì=Friday; sabato=Saturday'),
  DAYS_OF_WEEK__4: V('domenica=Sunday', ['The week starts on lunedì in Italy, so domenica comes last.']),
  ASK_STATE_DAY: R(
    ['Che giorno è oggi? means “What day is it today?”. Che is “what”, giorno is “day”, è is “is” and oggi is “today”.', 'To answer, say Oggi è and then the day: Oggi è lunedì means “Today is Monday”.'],
    [],
    { say: [['How do you ask “What day is it today?”', 'Che giorno è oggi'], ['How do you say “Today is Monday”?', 'Oggi è lunedì']] },
  ),
  MONTHS_YEAR: V('gennaio=January; febbraio=February', ['Italian months start with a small letter.']),
  MONTHS_YEAR__2: V('marzo=March; aprile=April'),
  MONTHS_YEAR__3: V('maggio=May; giugno=June'),
  MONTHS_YEAR__4: V('luglio=July; agosto=August'),
  MONTHS_YEAR__5: V('settembre=September; ottobre=October'),
  MONTHS_YEAR__6: V('novembre=November; dicembre=December'),
  DATE_FORMULA: R(
    ['To say a date, use il + the number + the month.', 'Il cinque maggio means “the fifth of May”, which is 5 May.', 'Il dieci agosto means “10 August”.'],
    [],
    { say: [['How do you say “5 May”?', 'il cinque maggio'], ['How do you say “10 August”?', 'il dieci agosto']] },
  ),
  SEASONS: V('primavera=spring; estate=summer'),
  SEASONS__2: V('autunno=autumn; inverno=winter'),
  IL_PRIMO_EXCEPTION: R(
    ['The first of the month is the exception: Italian says il primo, “the first”, instead of the number uno.', 'Il primo maggio means “1 May”.', 'Every other day uses an ordinary number: il due maggio, il tre maggio.'],
    [['Which is the correct way to say “1 May”?', 'il primo maggio', 'il uno maggio']],
    { say: [['How do you say “1 May”?', 'il primo maggio']] },
  ),
  AVERE_VERB: V('ho=I have; hai=you have (one friend)', ['These are forms of the verb avere, “to have”.']),
  AVERE_VERB__2: V('ha=he / she has; abbiamo=we have'),
  AVERE_VERB__3: V('avete=you (more than one person) have; hanno=they have'),
  CHE_ORE_SONO: R(
    ['Che ore sono? means “What time is it?”. Literally it asks “What hours are they?”.', 'Che is “what”, ore is “hours” and sono is “are”.'],
    [],
    { say: [['How do you ask “What time is it?”', 'Che ore sono']] },
  ),
  SONO_LE: R(
    ['To tell the time, start with Sono le and add the hour: Sono le tre means “It is three o’clock”.', 'Sono le cinque means “It is five o’clock”.', 'One o’clock is the one exception: it is È l’una.'],
    [],
    { say: [['How do you say “It is three o’clock”?', 'Sono le tre'], ['How do you say “It is five o’clock”?', 'Sono le cinque']] },
  ),
  E_MENO_QUARTER_HALF: R(
    ['After the hour, use e for “past”: Sono le tre e un quarto means “It is a quarter past three”.', 'Mezza means “half”: Sono le tre e mezza means “It is half past three”.', 'Before the next hour, use meno for “to”: Sono le quattro meno un quarto means “It is a quarter to four”.'],
    [['How do you say “quarter past three”?', 'Sono le tre e un quarto', 'Sono le tre meno un quarto'], ['Which word means “to” (before the hour)?', 'meno', 'e']],
  ),
  MEZZOGIORNO_MEZZANOTTE: V('mezzogiorno=noon; mezzanotte=midnight', ['Say È mezzogiorno for “It is noon” and È mezzanotte for “It is midnight”.']),
  QUANTI_ANNI_HAI: R(
    ['Quanti anni hai? means “How old are you?”.', 'Literally it asks “How many years do you have?”, because Italian uses avere, “to have”, for age.'],
    [],
    { say: [['How do you ask a friend “How old are you?”', 'Quanti anni hai']] },
  ),
  HO_ANNI: R(
    ['To say your age, use ho, “I have”, and anni, “years”: Ho venti anni means “I am twenty years old”.', 'Do not use essere (sono) for age. Italian says “I have twenty years”.'],
    [['Which is the correct way to say “I am twenty years old”?', 'Ho venti anni', 'Sono venti anni']],
    { say: [['How do you say “I am twenty years old”?', 'Ho venti anni']] },
  ),
};
