'use strict';
const { V, R } = require('./helpers');

// A1.5 Family, description and common irregular verbs
module.exports = {
  PRON2_SG: V('io=I; tu=you (one friend)'),
  PRON2_SG__2: V('lui=he; lei=she'),
  PRON2_PL: V('noi=we; voi=you (more than one person)'),
  PRON2_PL__2: V('loro=they'),
  FAM_1: V('la madre=mother; il padre=father', ['Mamma and papà are the everyday words for “mum” and “dad”.']),
  FAM_1__2: V('il fratello=brother; la sorella=sister'),
  FAM_2: V('il nonno=grandfather; la nonna=grandmother'),
  FAM_2__2: V('il figlio=son; la figlia=daughter'),
  ADJ_AGREEMENT: R(
    ['An adjective matches its noun in gender and number: un fratello alto (a tall brother), una sorella alta (a tall sister), due fratelli alti, due sorelle alte.', 'Alto means “tall”.'],
    [['A tall sister: una sorella ___', 'alta', 'alto'], ['Two tall brothers: due fratelli ___', 'alti', 'alte']],
  ),
  FAM_3: V('il marito=husband; la moglie=wife'),
  FAM_3__2: V('lo zio=uncle; la zia=aunt'),
  FAM_4: V('il cugino=cousin (male); la cugina=cousin (female)', ['The word changes with the person’s gender: cugino for a man, cugina for a woman.']),
  POSS_ADJ_FORMS: V('il mio=my (masculine); la mia=my (feminine)', ['Il mio libro means “my book” and la mia casa means “my house”.', 'Possessives usually have the article in front: il mio, la mia.']),
  POSS_ADJ_FORMS__2: V('i miei=my (masculine plural); le mie=my (feminine plural)', ['I miei libri means “my books” and le mie case means “my houses”.']),
  POSS_ADJ_EXCEPTION: R(
    ['With a singular family member, Italian drops the article before the possessive: mia madre (my mother), mio padre (my father), not la mia madre.', 'Plural family members keep the article: i miei genitori (my parents), le mie sorelle (my sisters).'],
    [['“My mother”', 'mia madre', 'la mia madre'], ['“My sisters”', 'le mie sorelle', 'mie sorelle']],
  ),
  PHYS_APPEARANCE_ADJ: V('alto=tall; basso=short', ['Both change with the person: alta and bassa for a woman.']),
  PHYS_APPEARANCE_ADJ__2: V('giovane=young; vecchio=old', ['Giovane stays the same for men and women. Vecchio becomes vecchia for a woman.']),
  PERSONALITY_ADJ: V('simpatico=nice; antipatico=unpleasant', ['Both change with the person: simpatica and antipatica for a woman.']),
  ESSERE_AVERE: R(
    ['Use essere (to be) for who somebody is and what they are like: Marco è alto.', 'Use avere (to have) for what somebody has, including age and feelings: Marco ha venti anni.'],
    [['Which verb goes with age: “He is twenty”?', 'Ha venti anni', 'È venti anni'], ['Which verb goes with a description: “He is tall”?', 'È alto', 'Ha alto']],
  ),
  PRESENT_REGULAR: R(
    ['Regular verbs follow a pattern: remove -are, -ere or -ire from the infinitive and add the endings for the person.', 'Io parlo, tu parli, lui parla, noi parliamo, voi parlate, loro parlano.'],
    [['“I speak”', 'parlo', 'parli'], ['“We speak”', 'parliamo', 'parlano']],
  ),
  FARE_SG: V('faccio=I do / I make; fai=you do / you make', ['Fare means “to do” and “to make”, and it is irregular.']),
  FARE_SG__2: V('fa=he / she does / makes'),
  VOLERE_SG: V('voglio=I want; vuoi=you want', ['Volere means “to want”, and it is irregular.']),
  VOLERE_SG__2: V('vuole=he / she wants'),
  FARE_PL: V('facciamo=we do / we make; fate=you (more than one person) do / make'),
  FARE_PL__2: V('fanno=they do / they make'),
  POTERE_SG: V('posso=I can; puoi=you can', ['Potere means “to be able to”, and it is irregular.']),
  POTERE_SG__2: V('può=he / she can'),
  DOVERE_SG: V('devo=I must; devi=you must', ['Dovere means “to have to”, and it is irregular.']),
  DOVERE_SG__2: V('deve=he / she must'),
  ANDARE_SG: V('vado=I go; vai=you go', ['Andare means “to go”, and it is irregular.']),
  ANDARE_SG__2: V('va=he / she goes'),
  DOVERE_PL: V('dobbiamo=we must; dovete=you (more than one person) must'),
  DOVERE_PL__2: V('devono=they must'),
  DARE: V('do=I give; dai=you give', ['Dare means “to give”, and it is irregular.']),
  DARE__2: V('dà=he / she gives; diamo=we give', ['Dà has an accent so that it is not confused with da, “from”.']),
  DARE__3: V('date=you (more than one person) give; danno=they give'),
  STARE: V('sto=I am (how I am / where I stay); stai=you are', ['Stare means “to stay” or “to be” for how you are: Sto bene means “I am well”.']),
  STARE__2: V('sta=he / she is; stiamo=we are'),
  STARE__3: V('state=you (more than one person) are; stanno=they are'),
  INFINITIVE_FORM: R(
    ['The infinitive is the form of a verb that means “to ___” and ends in -are, -ere or -ire: parlare (to speak), prendere (to take), dormire (to sleep).', 'It is the form you find in a dictionary.'],
    [['Which of these is an infinitive?', 'parlare', 'parlo'], ['What does the infinitive dormire mean?', 'to sleep', 'I sleep']],
  ),
  VOLERE_PL: V('vogliamo=we want; volete=you (more than one person) want'),
  VOLERE_PL__2: V('vogliono=they want'),
  ANDARE_PL: V('andiamo=we go; andate=you (more than one person) go'),
  ANDARE_PL__2: V('vanno=they go'),
  POTERE_PL: V('possiamo=we can; potete=you (more than one person) can'),
  POTERE_PL__2: V('possono=they can'),
  DESCRIBE_PEOPLE: R(
    ['To describe a person’s looks or character, use essere with an adjective: Mia sorella è alta e simpatica (My sister is tall and nice).', 'Use avere for some features: Ha i capelli lunghi (She has long hair).'],
    [['“My brother is tall”', 'Mio fratello è alto', 'Mio fratello ha alto']],
  ),
  MODAL_INFINITIVE_CONSTRUCTION: R(
    ['After potere and dovere, the next verb stays in the infinitive: Posso parlare means “I can speak”, and Devo andare means “I must go”.', 'The first verb changes with the person and the second does not.'],
    [['“I can speak”', 'Posso parlare', 'Posso parlo'], ['“I must go”', 'Devo andare', 'Devo vado']],
  ),
  MODAL_INFINITIVE_CONSTRUCTION__2: R(
    ['Volere works the same way: Voglio mangiare means “I want to eat”.', 'The second verb stays in the infinitive: Vuole dormire means “He / she wants to sleep”.'],
    [['“I want to eat”', 'Voglio mangiare', 'Voglio mangio']],
  ),
};
